//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOCATE_D_MERGE
    {
        public string ids { get; set; }
        public string allocate_id { get; set; }
        public string allocate_d_ids { get; set; }
        public string cerpcode { get; set; }
        public string cstatus { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<decimal> toallocount { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string ctopositioncode { get; set; }
        public string ctoposition { get; set; }
        public string allo_type { get; set; }
        public Nullable<decimal> sptype { get; set; }
        public Nullable<decimal> is_scan { get; set; }
        public Nullable<decimal> part_bond { get; set; }
        public string define1 { get; set; }
        public string define2 { get; set; }
        public string define3 { get; set; }
    
        public virtual ALLOCATE ALLOCATE { get; set; }
    }
}
