//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOCATE_SCAN_QTY
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string scanuser { get; set; }
        public Nullable<System.DateTime> scandate { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string allocate_d_ids { get; set; }
        public string scan_sn { get; set; }
        public Nullable<decimal> scan_qty { get; set; }
        public Nullable<decimal> scan_type { get; set; }
    }
}
