//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRS_SHOWINFO
    {
        public string id { get; set; }
        public Nullable<int> seq { get; set; }
        public string ctype { get; set; }
        public string operationname { get; set; }
        public string LineId { get; set; }
        public string siteid { get; set; }
        public string caseid { get; set; }
        public string casetype { get; set; }
        public string message { get; set; }
        public string CDefine1 { get; set; }
        public string CDefine2 { get; set; }
        public string CDefine3 { get; set; }
        public System.DateTime createtime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<int> isshow { get; set; }
    }
}
