//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_REPACK
    {
        public string id { get; set; }
        public string repack_no { get; set; }
        public decimal type { get; set; }
        public string repackid { get; set; }
        public string repackid_his { get; set; }
        public System.DateTime repack_date { get; set; }
        public string repack_owner { get; set; }
        public System.DateTime createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastmodifytime { get; set; }
        public string lastmodifyowner { get; set; }
    }
}
