//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_CARTON_D
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinbarid { get; set; }
        public string cinvbarcode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastmodifytime { get; set; }
        public string lastmodifyowner { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> handle_status { get; set; }
    
        public virtual BAR_CARTON_M BAR_CARTON_M { get; set; }
    }
}
