//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_TYPE
    {
        public string id { get; set; }
        public string typename { get; set; }
        public string type { get; set; }
        public string barcode_type { get; set; }
        public string mix { get; set; }
        public Nullable<decimal> max_qty { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string craeteowner { get; set; }
        public Nullable<System.DateTime> lastmodifytime { get; set; }
        public string lastmodifyowner { get; set; }
    }
}
