//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_PALLET_D_HIS
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cartonid { get; set; }
        public string cartoncode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> lastmodifytime { get; set; }
        public string lastmodifyowner { get; set; }
    }
}
