//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_PALLET_M_HIS
    {
        public string id { get; set; }
        public string palletno { get; set; }
        public string palletname { get; set; }
        public string type_id { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastmodifytime { get; set; }
        public string lastmodifyownre { get; set; }
    }
}
