//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PART_AREA_XX
    {
        public string partnumber { get; set; }
        public string area_id { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string ccreateowner { get; set; }
        public Nullable<decimal> ipriority { get; set; }
    }
}
