//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_BARCODE_PRINT_D
    {
        public string Id { get; set; }
        public string PrintId { get; set; }
        public int PrintSeq { get; set; }
        public string PrintItemName { get; set; }
        public string PrintItemType { get; set; }
        public string PrintRemark { get; set; }
        public string IsNeedVal { get; set; }
    }
}
