//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CRANECONFIG
    {
        public string ID { get; set; }
        public string CRANEID { get; set; }
        public string CRANENAME { get; set; }
        public string CRANEIP { get; set; }
        public string GROUPID { get; set; }
        public Nullable<int> SITECOUNT { get; set; }
        public string FLAG { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string PLCType { get; set; }
        public string SUPPLIER { get; set; }
        public string CREATEUSER { get; set; }
        public string MODIFYUSER { get; set; }
        public string EQUIPMENTNAME { get; set; }
        public string TTYPE { get; set; }
        public string DISCONTINUEUSER { get; set; }
        public Nullable<System.DateTime> DISCONTINUETIME { get; set; }
    }
}
