//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PART_TEMP
    {
        public string cspecifications { get; set; }
        public string inw { get; set; }
        public string icw { get; set; }
        public string cunits { get; set; }
        public string ineedcheck { get; set; }
        public string cinrule { get; set; }
        public string coutrule { get; set; }
        public string ilength { get; set; }
        public string iwidth { get; set; }
        public string iheight { get; set; }
        public string cusetype { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string ddefine3 { get; set; }
        public string ddefine4 { get; set; }
        public string idefine5 { get; set; }
        public string cmemo { get; set; }
        public string dexpiredate { get; set; }
        public string calias { get; set; }
        public string cerpcode { get; set; }
        public string csafeqty { get; set; }
        public string ineedwarn { get; set; }
        public string cstatus { get; set; }
        public string cpartnumber { get; set; }
        public string cpartname { get; set; }
        public string ctype { get; set; }
        public string cdefaultware { get; set; }
        public string cdefaultcargo { get; set; }
        public string cversion { get; set; }
        public string cbarrule { get; set; }
        public string cdefaultvendor { get; set; }
        public string cvolume { get; set; }
        public string createtime { get; set; }
        public string createowner { get; set; }
        public string lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string bonded { get; set; }
        public string mtype { get; set; }
        public string exp_days { get; set; }
        public string volumeunits { get; set; }
        public string referunit { get; set; }
        public string baseunit { get; set; }
        public string companyno { get; set; }
        public string strongholdno { get; set; }
        public string organizationno { get; set; }
        public string id { get; set; }
        public Nullable<decimal> flag { get; set; }
        public string needserial { get; set; }
    }
}
