//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_ASRS_DB
    {
        public string id { get; set; }
        public string db_ip { get; set; }
        public string db_datebase { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateuser { get; set; }
    }
}
