//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PART_CARGOSPACE
    {
        public string cpartnumber { get; set; }
        public string cwareid { get; set; }
        public string cpositioncode { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime cdatetime { get; set; }
        public string id { get; set; }
    }
}
