//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CRANECONFIG_DETIAL_SCAN
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string siteid { get; set; }
        public string scanid { get; set; }
        public string scanname { get; set; }
        public string scanip { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public string updateuser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string ScanType { get; set; }
        public string DISCONTINUEUSER { get; set; }
        public Nullable<System.DateTime> DISCONTINUETIME { get; set; }
        public string serverscanip { get; set; }
        public string scanportno { get; set; }
    }
}
