//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_DOCUREASON
    {
        public string id { get; set; }
        public string actionscope { get; set; }
        public string states { get; set; }
        public string reasoncode { get; set; }
        public string reasoncontent { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string ccreateownercode { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string isfromerp { get; set; }
    }
}
