//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_SERIAL_NUMBER
    {
        public string id { get; set; }
        public string cticketcode { get; set; }
        public string billcticketcode { get; set; }
        public string cerpcode { get; set; }
        public string cinvcode { get; set; }
        public string serialno { get; set; }
        public decimal quantity { get; set; }
        public string dtype { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string ccreateuser { get; set; }
        public string lastupdateuser { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string cdefine3 { get; set; }
        public string cdefine4 { get; set; }
        public string cdefine5 { get; set; }
        public string cdefine6 { get; set; }
    }
}
