//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_BARCODE_RULE_D
    {
        public string ID { get; set; }
        public string RULEID { get; set; }
        public Nullable<int> SNO { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ILENGTH { get; set; }
        public Nullable<int> IFROM { get; set; }
        public Nullable<int> ITO { get; set; }
        public string BARCODETYPEID { get; set; }
        public string FORMATID { get; set; }
        public string DEFAULTVALUE { get; set; }
        public string MANDATORY { get; set; }
        public string REMARK { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string MODIFYUSER { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
