//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_TV_ShowInfo
    {
        public string id { get; set; }
        public string lineid { get; set; }
        public string siteid { get; set; }
        public string palletcode { get; set; }
        public string mode { get; set; }
        public string wmstskid { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
