//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_DEPARTMENT_OTYPE
    {
        public string id { get; set; }
        public string departmentno { get; set; }
        public string departmentname { get; set; }
        public string typecode { get; set; }
        public string typename { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
    }
}
