//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_FILEUPLOD
    {
        public string id { get; set; }
        public string filename { get; set; }
        public string newfilename { get; set; }
        public string suffix { get; set; }
        public string filesize { get; set; }
        public string path { get; set; }
        public string po { get; set; }
        public string prantno { get; set; }
        public string lusn { get; set; }
        public string luno { get; set; }
        public string sn { get; set; }
    }
}
