//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CRANECONFIG_PLCADDR
    {
        public string ID { get; set; }
        public string IDS { get; set; }
        public string PLCREGION { get; set; }
        public string PLCADDRESS { get; set; }
        public string MEANING { get; set; }
        public string ASCRIPTION { get; set; }
        public string REMARK { get; set; }
        public string CREATERUSER { get; set; }
        public Nullable<System.DateTime> CREATERTIME { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string DEFINE1 { get; set; }
        public Nullable<System.DateTime> DEFINE2 { get; set; }
        public string DEFINE3 { get; set; }
        public Nullable<System.DateTime> DEFINE4 { get; set; }
    }
}
