//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseRGV_TV_PackageNo
    {
        public string ID { get; set; }
        public string LINEID { get; set; }
        public string RGVAREAID { get; set; }
        public string PACKAGENO { get; set; }
        public string CREATEUSER { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string REMARK { get; set; }
    }
}
