//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PART
    {
        public string cspecifications { get; set; }
        public Nullable<decimal> inw { get; set; }
        public Nullable<decimal> icw { get; set; }
        public string cunits { get; set; }
        public Nullable<decimal> ineedcheck { get; set; }
        public string cinrule { get; set; }
        public string coutrule { get; set; }
        public Nullable<decimal> ilength { get; set; }
        public Nullable<decimal> iwidth { get; set; }
        public Nullable<decimal> iheight { get; set; }
        public string cusetype { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cmemo { get; set; }
        public Nullable<System.DateTime> dexpiredate { get; set; }
        public string calias { get; set; }
        public string cerpcode { get; set; }
        public Nullable<decimal> csafeqty { get; set; }
        public Nullable<decimal> ineedwarn { get; set; }
        public string id { get; set; }
        public string cstatus { get; set; }
        public string cpartnumber { get; set; }
        public string cpartname { get; set; }
        public string ctype { get; set; }
        public string cdefaultware { get; set; }
        public string cdefaultcargo { get; set; }
        public string cversion { get; set; }
        public string cbarrule { get; set; }
        public string cdefaultvendor { get; set; }
        public Nullable<decimal> cvolume { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public Nullable<decimal> mtype { get; set; }
        public Nullable<decimal> bonded { get; set; }
        public Nullable<decimal> exp_days { get; set; }
        public string productcode { get; set; }
        public Nullable<decimal> boxnum { get; set; }
        public string UNIT { get; set; }
        public Nullable<int> NeedSerial { get; set; }
        public Nullable<decimal> csafeqtyceiling { get; set; }
    }
}
