//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_DOCUCLASS
    {
        public string ID { get; set; }
        public string DOCUTYPECODE { get; set; }
        public string DOCUNAME { get; set; }
        public string MODULETYPE { get; set; }
        public string MODULENAME { get; set; }
        public string DOCUNATURE { get; set; }
        public string JOBNUMBER { get; set; }
        public string JOBNAME { get; set; }
        public Nullable<System.DateTime> DCREATETIME { get; set; }
        public string CCREATEOWNERCODE { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string LASTUPDATEOWNER { get; set; }
    }
}
