//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_INTERFACELOG
    {
        public string ID { get; set; }
        public string TICKETCODE { get; set; }
        public string ERPCODE { get; set; }
        public string TYPEID { get; set; }
        public string METHODNAME { get; set; }
        public string ERRORMSG { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEOWNER { get; set; }
        public string REMARK { get; set; }
        public string BO { get; set; }
        public string TYPENAME { get; set; }
    }
}
