//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_TypeMapping
    {
        public string ID { get; set; }
        public string WMS_TypeCode { get; set; }
        public string WMS_TypeName { get; set; }
        public string ERP_TypeCode { get; set; }
        public string ERP_TypeName { get; set; }
        public string type { get; set; }
        public string CStatus { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string dcreateuser { get; set; }
    }
}
