//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_BAR_SN
    {
        public string id { get; set; }
        public string sn_code { get; set; }
        public string datecode { get; set; }
        public string bonded { get; set; }
        public Nullable<decimal> validitydate { get; set; }
        public string vendor { get; set; }
        public string vendor_name { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public string cinvcode { get; set; }
        public string cinvcode_name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string sn_type { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> last_upd_time { get; set; }
        public string last_upd_owner { get; set; }
        public string cpositioncode { get; set; }
        public string po_number { get; set; }
        public string batch_number { get; set; }
        public Nullable<decimal> batch_qty { get; set; }
        public string bar_type { get; set; }
        public Nullable<decimal> boxNum { get; set; }
        public string BarCodeType { get; set; }
        public string Po_LineId { get; set; }
        public string So_Number { get; set; }
        public string So_LineId { get; set; }
        public string ClientCode { get; set; }
        public string ClinetName { get; set; }
        public string ArbitraryVal1 { get; set; }
        public string ArbitraryVal2 { get; set; }
        public string ArbitraryVal3 { get; set; }
        public string ArbitraryVal4 { get; set; }
        public string ArbitraryVal5 { get; set; }
        public string ArbitraryVal6 { get; set; }
        public string ArbitraryVal7 { get; set; }
        public string ArbitraryVal8 { get; set; }
        public string ArbitraryVal9 { get; set; }
        public string ArbitraryVal10 { get; set; }
        public string CodeRuleId { get; set; }
        public string PrintRuleId { get; set; }
        public string PrintVal1 { get; set; }
        public string PrintVal2 { get; set; }
        public string PrintVal3 { get; set; }
        public string PrintVal4 { get; set; }
        public string PrintVal5 { get; set; }
        public string PrintVal6 { get; set; }
        public string PrintVal7 { get; set; }
        public string PrintVal8 { get; set; }
        public string PrintVal9 { get; set; }
        public string PrintVal10 { get; set; }
    }
}
