//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_BARCODE_PRINT
    {
        public string Id { get; set; }
        public string PrintCode { get; set; }
        public string PrintName { get; set; }
        public string BarCodeType { get; set; }
        public string Cstatus { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EnableUser { get; set; }
        public Nullable<System.DateTime> EnableTime { get; set; }
        public string DisableUser { get; set; }
        public Nullable<System.DateTime> DisableTime { get; set; }
        public string Remark { get; set; }
    }
}
