//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserLanguage
    {
        public string ID { get; set; }
        public string UserNo { get; set; }
        public string UserName { get; set; }
        public string Project { get; set; }
        public string LanguageId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Remark { get; set; }
    }
}
