//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_LINE_LIST
    {
        public string id { get; set; }
        public string lineid { get; set; }
        public Nullable<decimal> cstatus { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string last_upd_owner { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
        public Nullable<decimal> is_merge { get; set; }
    }
}
