//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_PackageScan
    {
        public string ID { get; set; }
        public string PackageNO { get; set; }
        public string IP { get; set; }
        public string MachineID { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ScanType { get; set; }
        public string Remark { get; set; }
        public string CDefine1 { get; set; }
        public string CDefine2 { get; set; }
        public string CDefine3 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
