//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CRANECONFIG_D_Trade
    {
        public string IDS { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ERPCode { get; set; }
        public string CraneID { get; set; }
        public string CraneName { get; set; }
        public string SIteID { get; set; }
        public string SIteName { get; set; }
    }
}
