//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_BARCODE_RULE
    {
        public string ID { get; set; }
        public string RULECODE { get; set; }
        public string RULENAME { get; set; }
        public Nullable<int> RULELEN { get; set; }
        public string RULETYPE { get; set; }
        public string STATUS { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string MODIFYUSER { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string ENABLEUSER { get; set; }
        public Nullable<System.DateTime> ENABLEDATE { get; set; }
        public string DISABLEUSER { get; set; }
        public Nullable<System.DateTime> DISABLEDATE { get; set; }
        public string REMARK { get; set; }
        public string DefaultPrintId { get; set; }
    }
}
