//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CRANECONFIG_DETIAL
    {
        public string ID { get; set; }
        public string CRANEID { get; set; }
        public string SITEID { get; set; }
        public string SITENAME { get; set; }
        public string SITETYPE { get; set; }
        public string FLAG { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string DEFULSITE { get; set; }
        public string FORMAT { get; set; }
        public string REMARK { get; set; }
        public string IDS { get; set; }
        public string RELATIONSITE { get; set; }
        public string ISWHOLE { get; set; }
        public string ISMONITOR { get; set; }
        public string PLCREGION { get; set; }
        public string DISCONTINUEUSER { get; set; }
        public Nullable<System.DateTime> DISCONTINUETIME { get; set; }
        public string STOREY { get; set; }
        public string STOREYLIMIT { get; set; }
        public string AGVSITE { get; set; }
        public string RGVSITE { get; set; }
        public string AGVSITETYPE { get; set; }
        public string STORAGESITE { get; set; }
        public string YORDERBY { get; set; }
        public string IS_OCCUPY { get; set; }
        public string IS_DEFAULT_IN { get; set; }
        public string MONITORTYPE { get; set; }
    }
}
