//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_JOB_RunTime
    {
        public string ID { get; set; }
        public string JOBNAME { get; set; }
        public string JOBDESC { get; set; }
        public Nullable<System.DateTime> RUNTIME { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
    }
}
