//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Resources
    {
        public string ID { get; set; }
        public string SourceKey { get; set; }
        public string SourceValue { get; set; }
        public string LanguageId { get; set; }
        public string ModuleId { get; set; }
        public string Remark { get; set; }
        public string CDefined1 { get; set; }
        public string CDefined2 { get; set; }
        public string CDefined3 { get; set; }
        public string CDefined4 { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string CStatus { get; set; }
    }
}
