//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_MST_LOG
    {
        public int ID { get; set; }
        public Nullable<int> WmsTaskId { get; set; }
        public Nullable<int> StepId { get; set; }
        public string Msg { get; set; }
        public string LineId { get; set; }
        public string CTICKETCODE { get; set; }
        public string PACKAGENO { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remark { get; set; }
    }
}
