//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_AGVPositionCodeDetail
    {
        public string id { get; set; }
        public string taskid { get; set; }
        public string type { get; set; }
        public string positioncodepath { get; set; }
        public int codepathorder { get; set; }
        public string CreateOwner { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
