//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_EquipTask
    {
        public int id { get; set; }
        public int equiptype { get; set; }
        public string cmdsno { get; set; }
        public string cmdmode { get; set; }
        public string startstnno { get; set; }
        public string endstnno { get; set; }
        public string status { get; set; }
        public string trnno { get; set; }
        public string acttime { get; set; }
        public string endtime { get; set; }
        public string CreateOwner { get; set; }
        public System.DateTime Createtime { get; set; }
    }
}
