//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_MST
    {
        public int WmsTskId { get; set; }
        public string CmdSno { get; set; }
        public string CmdSts { get; set; }
        public string PRT { get; set; }
        public string StnNo { get; set; }
        public string CmdMode { get; set; }
        public string Loc { get; set; }
        public string NewLoc { get; set; }
        public string LocSize { get; set; }
        public string RodID { get; set; }
        public string Trace { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string Result { get; set; }
        public string TrnNo { get; set; }
        public Nullable<int> BILLINGSTATUS { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<int> UPDATA { get; set; }
        public string CMDNO { get; set; }
        public string LINEID { get; set; }
        public string CTICKETCODE { get; set; }
        public string PACKAGENO { get; set; }
        public string REMARK { get; set; }
        public string PLCD51 { get; set; }
        public string BillingNO { get; set; }
        public string MSG { get; set; }
        public string TaskNO { get; set; }
        public string SourceWmsTskId { get; set; }
    }
}
