//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMDByPalletCode
    {
        public string id { get; set; }
        public string stntype { get; set; }
        public string stnno { get; set; }
        public string PalletCode { get; set; }
        public string code { get; set; }
        public string message { get; set; }
        public string data { get; set; }
    }
}
