//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CX_FLOW_SWR_INFO
    {
        public string bu { get; set; }
        public string current_owner { get; set; }
        public string current_process { get; set; }
        public string current_status { get; set; }
        public string customer { get; set; }
        public string eng_dept_name { get; set; }
        public Nullable<System.DateTime> fpm_sign_time { get; set; }
        public string new_pn { get; set; }
        public string old_pn { get; set; }
        public Nullable<System.DateTime> pmc_sign_time { get; set; }
        public string process { get; set; }
        public string rework_comment { get; set; }
        public string rework_detial_info { get; set; }
        public Nullable<decimal> rework_qty { get; set; }
        public string so { get; set; }
        public string spec { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public string submit_emp { get; set; }
        public string swr_no { get; set; }
        public Nullable<System.DateTime> tw_sign_time { get; set; }
        public string work_order { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
