//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT_LINE_INFO
    {
        public string id { get; set; }
        public string departmentno { get; set; }
        public decimal type { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
    }
}
