//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANDLE_LOG
    {
        public string id { get; set; }
        public string userno { get; set; }
        public System.DateTime opttime { get; set; }
        public string handle_type { get; set; }
        public string handle_table { get; set; }
        public string record_id { get; set; }
        public string reservefield1 { get; set; }
        public string reservefield2 { get; set; }
        public string reservefield3 { get; set; }
        public string reservefield4 { get; set; }
        public string reservefield5 { get; set; }
        public string reservefield6 { get; set; }
        public string reservefield7 { get; set; }
        public string reservefield8 { get; set; }
    }
}
