//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_MERGE_PALLETE
    {
        public string ID { get; set; }
        public string INASNCODE { get; set; }
        public string PALLETCODE { get; set; }
        public string ERPCODE { get; set; }
        public string OUTASNCODE_PALLET { get; set; }
        public string OUTBILLCODE_PALLET { get; set; }
        public string INASNCODE_PALLET { get; set; }
        public string INBILLCODE_PALLET { get; set; }
        public string CSTATUS { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYUSER { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public string CDEFINE4 { get; set; }
        public string REMARK { get; set; }
    }
}
