//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INASN
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditpersoncode { get; set; }
        public Nullable<System.DateTime> dauditdate { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string cpo { get; set; }
        public string itype { get; set; }
        public string cmemo { get; set; }
        public string cerpcode { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string ddefine3 { get; set; }
        public string ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cvendercode { get; set; }
        public string cvender { get; set; }
        public string inasn_ia_id { get; set; }
        public Nullable<decimal> specil_return { get; set; }
        public Nullable<decimal> critical_part { get; set; }
        public string reasoncode { get; set; }
        public string reasoncontent { get; set; }
        public string WORKTYPE { get; set; }
        public string SPLITCASENO { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string HYNum { get; set; }
        public string Slpname { get; set; }
    }
}
