//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INASN_D_APP_BAK
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cstatus { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cinvbarcode { get; set; }
        public string cbatch { get; set; }
        public string cmemo { get; set; }
        public string cerpcodeline { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cpo { get; set; }
        public Nullable<decimal> ipoline { get; set; }
        public string erpcodelinenum { get; set; }
        public string po_numbername { get; set; }
        public string po_linenumbername { get; set; }
        public Nullable<decimal> manual { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string inasn_ia_d_ids { get; set; }
        public Nullable<int> LineID { get; set; }
        public string Unit { get; set; }
        public string DfWHSCode { get; set; }
        public string DfSHSCode { get; set; }
        public string REASONCODE { get; set; }
    }
}
