//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INASN_D_ISTOCK_SPLIT
    {
        public string id { get; set; }
        public string ASN_ID { get; set; }
        public string ASN_D_IDS { get; set; }
        public string CINVCODE { get; set; }
        public string FLAG { get; set; }
        public Nullable<decimal> OLDQTY { get; set; }
        public Nullable<decimal> CJQTY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
    }
}
