//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INBILL_D_BN
    {
        public string id { get; set; }
        public string SNIDS { get; set; }
        public string BN_code { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastvpdtime { get; set; }
        public string lastvpdowner { get; set; }
        public string worktype { get; set; }
        public string istransed { get; set; }
        public Nullable<System.DateTime> transedtime { get; set; }
        public string union_id { get; set; }
        public string scan_ids { get; set; }
        public Nullable<decimal> bntype { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public string furnaceno { get; set; }
        public string BN_CODE20 { get; set; }
    }
}
