//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INPO()
        {
            this.INPO_D = new HashSet<INPO_D>();
        }
    
        public string id { get; set; }
        public string pono { get; set; }
        public string potype { get; set; }
        public Nullable<System.DateTime> podate { get; set; }
        public string vendorid { get; set; }
        public string vendorname { get; set; }
        public string currency { get; set; }
        public string paymentterm { get; set; }
        public string shipfrom { get; set; }
        public string shipto { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> source { get; set; }
        public string memo { get; set; }
        public string define1 { get; set; }
        public string define2 { get; set; }
        public string define3 { get; set; }
        public Nullable<System.DateTime> define4 { get; set; }
        public Nullable<decimal> define5 { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INPO_D> INPO_D { get; set; }
    }
}
