//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERFACE_LOST_TEMP
    {
        public System.DateTime transaction_date { get; set; }
        public string attribute11 { get; set; }
        public Nullable<decimal> transaction_source_id { get; set; }
        public string subinventory_code { get; set; }
        public Nullable<decimal> locator_id { get; set; }
        public Nullable<decimal> inventory_item_id { get; set; }
        public string attribute7 { get; set; }
        public Nullable<decimal> qty1 { get; set; }
        public Nullable<decimal> qty2 { get; set; }
    }
}
