//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTYPEBAK
    {
        public string typeid { get; set; }
        public string typename { get; set; }
        public string cerpcode { get; set; }
        public string transaction_action_id { get; set; }
        public string transaction_source_type_id { get; set; }
        public string attribute1 { get; set; }
        public string type_class { get; set; }
    }
}
