//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTYPE
    {
        public string typeid { get; set; }
        public string typename { get; set; }
        public string cerpcode { get; set; }
        public string transaction_action_id { get; set; }
        public string transaction_source_type_id { get; set; }
        public string attribute1 { get; set; }
        public string type_class { get; set; }
        public string is_zf { get; set; }
        public Nullable<System.DateTime> disable_date { get; set; }
        public string erp_source_typename { get; set; }
        public string erp_source_typecode { get; set; }
        public string enable { get; set; }
        public string enableuser { get; set; }
        public Nullable<System.DateTime> enabledate { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> Is_Query { get; set; }
        public string IsMatchSo { get; set; }
        public string IsMatchVendor { get; set; }
    }
}
