//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_SYSERROR
    {
        public string id { get; set; }
        public string sovrce_no { get; set; }
        public string errormsg { get; set; }
        public decimal type { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<int> errorcode { get; set; }
    }
}
