//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_REVOKE_TEMPINBILL
    {
        public string ID { get; set; }
        public string PALLETDCODE { get; set; }
        public string INBILLCODE { get; set; }
        public string CTICKETCODE { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
