//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class MO_CINVCODE_FLAG
    {
        public string mo { get; set; }
        public string cinvcode { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> sequence { get; set; }
        public string oracleid { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string last_upd_owner { get; set; }
        public Nullable<System.DateTime> last_upd_time { get; set; }
        public string data_sources { get; set; }
        public string asn_code { get; set; }
        public Nullable<decimal> job_flag { get; set; }
    }
}
