//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class XUELONGEntities : DbContext
    {
        public XUELONGEntities()
            : base("name=XUELONGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLOCATE> ALLOCATE { get; set; }
        public virtual DbSet<ALLOCATE_D> ALLOCATE_D { get; set; }
        public virtual DbSet<ALLOCATE_D_BN> ALLOCATE_D_BN { get; set; }
        public virtual DbSet<ALLOCATE_D_HIS> ALLOCATE_D_HIS { get; set; }
        public virtual DbSet<ALLOCATE_D_MERGE> ALLOCATE_D_MERGE { get; set; }
        public virtual DbSet<ALLOCATE_D_SN> ALLOCATE_D_SN { get; set; }
        public virtual DbSet<ALLOCATE_HIS> ALLOCATE_HIS { get; set; }
        public virtual DbSet<ALLOCATE_SCAN_QTY> ALLOCATE_SCAN_QTY { get; set; }
        public virtual DbSet<BAR> BAR { get; set; }
        public virtual DbSet<BAR_CARTON> BAR_CARTON { get; set; }
        public virtual DbSet<BAR_CARTON_D> BAR_CARTON_D { get; set; }
        public virtual DbSet<BAR_CARTON_M> BAR_CARTON_M { get; set; }
        public virtual DbSet<BAR_PACK> BAR_PACK { get; set; }
        public virtual DbSet<BAR_PALLET> BAR_PALLET { get; set; }
        public virtual DbSet<BAR_PALLET_D> BAR_PALLET_D { get; set; }
        public virtual DbSet<BAR_PALLET_M> BAR_PALLET_M { get; set; }
        public virtual DbSet<BAR_REPACK> BAR_REPACK { get; set; }
        public virtual DbSet<BAR_SN_SPLIT> BAR_SN_SPLIT { get; set; }
        public virtual DbSet<BAR_SN_SPLIT_D> BAR_SN_SPLIT_D { get; set; }
        public virtual DbSet<BAR_TYPE> BAR_TYPE { get; set; }
        public virtual DbSet<BASE_AREA> BASE_AREA { get; set; }
        public virtual DbSet<BASE_ASRS_DB> BASE_ASRS_DB { get; set; }
        public virtual DbSet<BASE_BAR_SN> BASE_BAR_SN { get; set; }
        public virtual DbSet<BASE_BARCODE_PRINT> BASE_BARCODE_PRINT { get; set; }
        public virtual DbSet<BASE_BARCODE_PRINT_D> BASE_BARCODE_PRINT_D { get; set; }
        public virtual DbSet<BASE_BARCODE_RULE> BASE_BARCODE_RULE { get; set; }
        public virtual DbSet<BASE_BARCODE_RULE_D> BASE_BARCODE_RULE_D { get; set; }
        public virtual DbSet<BASE_BOM_D> BASE_BOM_D { get; set; }
        public virtual DbSet<BASE_CARGOSPACE> BASE_CARGOSPACE { get; set; }
        public virtual DbSet<BASE_CLIENT> BASE_CLIENT { get; set; }
        public virtual DbSet<BASE_CRANECONFIG> BASE_CRANECONFIG { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_D_Trade> BASE_CRANECONFIG_D_Trade { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_DETIAL> BASE_CRANECONFIG_DETIAL { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_DETIAL_SCAN> BASE_CRANECONFIG_DETIAL_SCAN { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_PLCADDR> BASE_CRANECONFIG_PLCADDR { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_TRADETYPE> BASE_CRANECONFIG_TRADETYPE { get; set; }
        public virtual DbSet<BASE_CRANECONFIG_TRADETYPE_D> BASE_CRANECONFIG_TRADETYPE_D { get; set; }
        public virtual DbSet<BASE_DELIVER_DEPARTMENT> BASE_DELIVER_DEPARTMENT { get; set; }
        public virtual DbSet<BASE_DEPARTMENT> BASE_DEPARTMENT { get; set; }
        public virtual DbSet<BASE_DOCUCLASS> BASE_DOCUCLASS { get; set; }
        public virtual DbSet<BASE_DOCUREASON> BASE_DOCUREASON { get; set; }
        public virtual DbSet<Base_Interface_RunTime> Base_Interface_RunTime { get; set; }
        public virtual DbSet<BASE_INTERFACELOG> BASE_INTERFACELOG { get; set; }
        public virtual DbSet<Base_JOB_RunTime> Base_JOB_RunTime { get; set; }
        public virtual DbSet<BASE_LINE_LIST> BASE_LINE_LIST { get; set; }
        public virtual DbSet<BASE_LINE_VENDOR> BASE_LINE_VENDOR { get; set; }
        public virtual DbSet<BASE_OPERATOR> BASE_OPERATOR { get; set; }
        public virtual DbSet<BASE_OPERATOR_AREA> BASE_OPERATOR_AREA { get; set; }
        public virtual DbSet<Base_PackageScan_New> Base_PackageScan_New { get; set; }
        public virtual DbSet<BASE_PART> BASE_PART { get; set; }
        public virtual DbSet<BASE_PART_CARGOSPACE> BASE_PART_CARGOSPACE { get; set; }
        public virtual DbSet<BASE_PART_TEMP> BASE_PART_TEMP { get; set; }
        public virtual DbSet<BASE_REPLACEPALLETCODE_RECORD> BASE_REPLACEPALLETCODE_RECORD { get; set; }
        public virtual DbSet<Base_Resources> Base_Resources { get; set; }
        public virtual DbSet<BASE_SENDEMAIL> BASE_SENDEMAIL { get; set; }
        public virtual DbSet<BASE_SERIAL_NUMBER> BASE_SERIAL_NUMBER { get; set; }
        public virtual DbSet<BASE_TV_ShowInfo> BASE_TV_ShowInfo { get; set; }
        public virtual DbSet<BASE_TypeMapping> BASE_TypeMapping { get; set; }
        public virtual DbSet<Base_UserLanguage> Base_UserLanguage { get; set; }
        public virtual DbSet<BASE_VENDOR> BASE_VENDOR { get; set; }
        public virtual DbSet<BASE_WAREHOUSE> BASE_WAREHOUSE { get; set; }
        public virtual DbSet<BASE_WAREHOUSE_TEMP> BASE_WAREHOUSE_TEMP { get; set; }
        public virtual DbSet<BaseRGV_AREA_PackageNo> BaseRGV_AREA_PackageNo { get; set; }
        public virtual DbSet<CMD_AGVPositionCodeDetail> CMD_AGVPositionCodeDetail { get; set; }
        public virtual DbSet<CMD_EquipTask> CMD_EquipTask { get; set; }
        public virtual DbSet<CMD_MST> CMD_MST { get; set; }
        public virtual DbSet<CMD_MST_LOG> CMD_MST_LOG { get; set; }
        public virtual DbSet<CMD_MST_RGV> CMD_MST_RGV { get; set; }
        public virtual DbSet<CMD_MST_Scan> CMD_MST_Scan { get; set; }
        public virtual DbSet<CMDByPalletCode> CMDByPalletCode { get; set; }
        public virtual DbSet<DATECODE_STOCK_CURRENT_DETAIL> DATECODE_STOCK_CURRENT_DETAIL { get; set; }
        public virtual DbSet<DEPARTMENT_LINE_INFO> DEPARTMENT_LINE_INFO { get; set; }
        public virtual DbSet<HANDLE_LOG> HANDLE_LOG { get; set; }
        public virtual DbSet<HD_SQLMAP> HD_SQLMAP { get; set; }
        public virtual DbSet<IN_MERGE_PALLETE> IN_MERGE_PALLETE { get; set; }
        public virtual DbSet<IN_MO_INFO> IN_MO_INFO { get; set; }
        public virtual DbSet<INASN> INASN { get; set; }
        public virtual DbSet<INASN_APP_BAK> INASN_APP_BAK { get; set; }
        public virtual DbSet<INASN_D> INASN_D { get; set; }
        public virtual DbSet<INASN_D_APP_BAK> INASN_D_APP_BAK { get; set; }
        public virtual DbSet<INASN_D_ISTOCK_SPLIT> INASN_D_ISTOCK_SPLIT { get; set; }
        public virtual DbSet<INASN_IA> INASN_IA { get; set; }
        public virtual DbSet<INASN_IA_D> INASN_IA_D { get; set; }
        public virtual DbSet<INASNCHANGE> INASNCHANGE { get; set; }
        public virtual DbSet<INASNCHANGE_D> INASNCHANGE_D { get; set; }
        public virtual DbSet<INASSIT> INASSIT { get; set; }
        public virtual DbSet<INASSIT_D> INASSIT_D { get; set; }
        public virtual DbSet<INBILL> INBILL { get; set; }
        public virtual DbSet<INBILL_D> INBILL_D { get; set; }
        public virtual DbSet<INBILL_D_BN> INBILL_D_BN { get; set; }
        public virtual DbSet<INBILL_D_SN> INBILL_D_SN { get; set; }
        public virtual DbSet<INPO> INPO { get; set; }
        public virtual DbSet<INPO_D> INPO_D { get; set; }
        public virtual DbSet<INTYPE> INTYPE { get; set; }
        public virtual DbSet<LOG_REVOKE_TEMPINBILL> LOG_REVOKE_TEMPINBILL { get; set; }
        public virtual DbSet<MO_DEPARTMENT> MO_DEPARTMENT { get; set; }
        public virtual DbSet<OUT_GROUP> OUT_GROUP { get; set; }
        public virtual DbSet<OUT_GROUP_D> OUT_GROUP_D { get; set; }
        public virtual DbSet<OUT_HANDOVER> OUT_HANDOVER { get; set; }
        public virtual DbSet<OUT_HANDOVER_CHECK> OUT_HANDOVER_CHECK { get; set; }
        public virtual DbSet<OUT_TRANSPORTATIONPLAN> OUT_TRANSPORTATIONPLAN { get; set; }
        public virtual DbSet<OUTASN> OUTASN { get; set; }
        public virtual DbSet<OUTASN_D> OUTASN_D { get; set; }
        public virtual DbSet<OUTASN_D_HIS> OUTASN_D_HIS { get; set; }
        public virtual DbSet<OUTASN_D_SPLIT> OUTASN_D_SPLIT { get; set; }
        public virtual DbSet<OUTASN_D_TEST> OUTASN_D_TEST { get; set; }
        public virtual DbSet<OUTASN_HIS> OUTASN_HIS { get; set; }
        public virtual DbSet<OUTASN_TEST> OUTASN_TEST { get; set; }
        public virtual DbSet<OUTASNCHANGE> OUTASNCHANGE { get; set; }
        public virtual DbSet<OUTASNCHANGE_D> OUTASNCHANGE_D { get; set; }
        public virtual DbSet<OUTASSIT> OUTASSIT { get; set; }
        public virtual DbSet<OUTASSIT_D> OUTASSIT_D { get; set; }
        public virtual DbSet<OUTASSIT_D_HIS> OUTASSIT_D_HIS { get; set; }
        public virtual DbSet<OUTASSIT_HIS> OUTASSIT_HIS { get; set; }
        public virtual DbSet<OUTBILL> OUTBILL { get; set; }
        public virtual DbSet<OUTBILL_D> OUTBILL_D { get; set; }
        public virtual DbSet<OUTBILL_D_BN> OUTBILL_D_BN { get; set; }
        public virtual DbSet<OUTBILL_D_HIS> OUTBILL_D_HIS { get; set; }
        public virtual DbSet<OUTBILL_D_SN> OUTBILL_D_SN { get; set; }
        public virtual DbSet<OUTBILL_HIS> OUTBILL_HIS { get; set; }
        public virtual DbSet<OUTMIXED> OUTMIXED { get; set; }
        public virtual DbSet<OUTMIXED_D> OUTMIXED_D { get; set; }
        public virtual DbSet<OUTORDER> OUTORDER { get; set; }
        public virtual DbSet<OUTORDER_D> OUTORDER_D { get; set; }
        public virtual DbSet<OUTTYPE> OUTTYPE { get; set; }
        public virtual DbSet<PROC_FUN_RETURN_INFO> PROC_FUN_RETURN_INFO { get; set; }
        public virtual DbSet<REPORT_PART_MORE_SPACE> REPORT_PART_MORE_SPACE { get; set; }
        public virtual DbSet<RPT_STOCK_DISCREPENCY> RPT_STOCK_DISCREPENCY { get; set; }
        public virtual DbSet<SalesOrder_D> SalesOrder_D { get; set; }
        public virtual DbSet<SalesOrder_M> SalesOrder_M { get; set; }
        public virtual DbSet<SnResetOperateInfo> SnResetOperateInfo { get; set; }
        public virtual DbSet<SSX_Site_Monitor> SSX_Site_Monitor { get; set; }
        public virtual DbSet<STOCK_ADJUST> STOCK_ADJUST { get; set; }
        public virtual DbSet<STOCK_CHECK_PLAN> STOCK_CHECK_PLAN { get; set; }
        public virtual DbSet<STOCK_CHECKBILL> STOCK_CHECKBILL { get; set; }
        public virtual DbSet<STOCK_CHECKBILL_D> STOCK_CHECKBILL_D { get; set; }
        public virtual DbSet<STOCK_CHECKEDBILL> STOCK_CHECKEDBILL { get; set; }
        public virtual DbSet<STOCK_CHECKEDBILL_SN> STOCK_CHECKEDBILL_SN { get; set; }
        public virtual DbSet<STOCK_CURRENT> STOCK_CURRENT { get; set; }
        public virtual DbSet<STOCK_CURRENT_ADJUST> STOCK_CURRENT_ADJUST { get; set; }
        public virtual DbSet<STOCK_CURRENT_ADJUST_D> STOCK_CURRENT_ADJUST_D { get; set; }
        public virtual DbSet<STOCK_CURRENT_BEGIN> STOCK_CURRENT_BEGIN { get; set; }
        public virtual DbSet<STOCK_CURRENT_BN> STOCK_CURRENT_BN { get; set; }
        public virtual DbSet<STOCK_CURRENT_DETAIL> STOCK_CURRENT_DETAIL { get; set; }
        public virtual DbSet<STOCK_CURRENT_OLD> STOCK_CURRENT_OLD { get; set; }
        public virtual DbSet<Stock_CURRENT_PalletCode> Stock_CURRENT_PalletCode { get; set; }
        public virtual DbSet<STOCK_CURRENT_SN> STOCK_CURRENT_SN { get; set; }
        public virtual DbSet<STOCK_CURRENT_SN_RESET> STOCK_CURRENT_SN_RESET { get; set; }
        public virtual DbSet<STOCK_DEDUCT_DETAIL> STOCK_DEDUCT_DETAIL { get; set; }
        public virtual DbSet<STOCK_DEDUCT_SN_DETAIL> STOCK_DEDUCT_SN_DETAIL { get; set; }
        public virtual DbSet<STOCK_DURATION> STOCK_DURATION { get; set; }
        public virtual DbSet<STOCK_SN_ERPUNLOCK> STOCK_SN_ERPUNLOCK { get; set; }
        public virtual DbSet<STOCK_SN_LOCK> STOCK_SN_LOCK { get; set; }
        public virtual DbSet<Sys_Area> Sys_Area { get; set; }
        public virtual DbSet<SYS_CONFIG> SYS_CONFIG { get; set; }
        public virtual DbSet<SYS_COUNTLOG> SYS_COUNTLOG { get; set; }
        public virtual DbSet<Sys_DbBackup> Sys_DbBackup { get; set; }
        public virtual DbSet<Sys_FilterIP> Sys_FilterIP { get; set; }
        public virtual DbSet<Sys_Items> Sys_Items { get; set; }
        public virtual DbSet<Sys_ItemsDetail> Sys_ItemsDetail { get; set; }
        public virtual DbSet<SYS_Job> SYS_Job { get; set; }
        public virtual DbSet<SYS_LOG_Type> SYS_LOG_Type { get; set; }
        public virtual DbSet<Sys_Module> Sys_Module { get; set; }
        public virtual DbSet<Sys_ModuleButton> Sys_ModuleButton { get; set; }
        public virtual DbSet<Sys_ModuleForm> Sys_ModuleForm { get; set; }
        public virtual DbSet<Sys_ModuleFormInstance> Sys_ModuleFormInstance { get; set; }
        public virtual DbSet<Sys_Organize> Sys_Organize { get; set; }
        public virtual DbSet<SYS_PARAMETER> SYS_PARAMETER { get; set; }
        public virtual DbSet<SYS_PARAMETERGROUP> SYS_PARAMETERGROUP { get; set; }
        public virtual DbSet<SYS_PARAMETERNAME> SYS_PARAMETERNAME { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_RoleAuthorize> Sys_RoleAuthorize { get; set; }
        public virtual DbSet<SYS_SCANINLOG> SYS_SCANINLOG { get; set; }
        public virtual DbSet<SYS_STOCKDIFF_LOG> SYS_STOCKDIFF_LOG { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserLogOn> Sys_UserLogOn { get; set; }
        public virtual DbSet<SYS_VERSION> SYS_VERSION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_TEST_FLOAT> TB_TEST_FLOAT { get; set; }
        public virtual DbSet<TEMP_AREA_PAET_WAREHOUSE> TEMP_AREA_PAET_WAREHOUSE { get; set; }
        public virtual DbSet<TEMP_BASE_AREA> TEMP_BASE_AREA { get; set; }
        public virtual DbSet<TEMP_BASE_CLIENT> TEMP_BASE_CLIENT { get; set; }
        public virtual DbSet<TEMP_BASE_DEPARTMENT> TEMP_BASE_DEPARTMENT { get; set; }
        public virtual DbSet<TEMP_BASE_LINE_LIST> TEMP_BASE_LINE_LIST { get; set; }
        public virtual DbSet<TEMP_BASE_PART_CARGOSPACE> TEMP_BASE_PART_CARGOSPACE { get; set; }
        public virtual DbSet<TEMP_BASE_STOCK_CURRENT> TEMP_BASE_STOCK_CURRENT { get; set; }
        public virtual DbSet<TEMP_BASE_VENDOR> TEMP_BASE_VENDOR { get; set; }
        public virtual DbSet<TEMP_DIGITALSINGE> TEMP_DIGITALSINGE { get; set; }
        public virtual DbSet<TEMP_IN_MO_INFO> TEMP_IN_MO_INFO { get; set; }
        public virtual DbSet<TEMP_INANDOUTBILL> TEMP_INANDOUTBILL { get; set; }
        public virtual DbSet<TEMP_INBILL_D> TEMP_INBILL_D { get; set; }
        public virtual DbSet<TEMP_OASN_ERPCODE_N> TEMP_OASN_ERPCODE_N { get; set; }
        public virtual DbSet<TEMP_OUTASN_ID> TEMP_OUTASN_ID { get; set; }
        public virtual DbSet<TEMP_OUTBILL_D> TEMP_OUTBILL_D { get; set; }
        public virtual DbSet<TEMP_OUTBILL_D_T> TEMP_OUTBILL_D_T { get; set; }
        public virtual DbSet<TEMP_OUTMIXED_D> TEMP_OUTMIXED_D { get; set; }
        public virtual DbSet<TEMP_SELECTASND> TEMP_SELECTASND { get; set; }
        public virtual DbSet<TEMP_STOCK_CHECK> TEMP_STOCK_CHECK { get; set; }
        public virtual DbSet<TEMP_STOCK_SNRESET> TEMP_STOCK_SNRESET { get; set; }
        public virtual DbSet<TEMP_TVShowInfo> TEMP_TVShowInfo { get; set; }
        public virtual DbSet<TRANS_LOG> TRANS_LOG { get; set; }
        public virtual DbSet<TRANSACTION_TIME_CONFIG> TRANSACTION_TIME_CONFIG { get; set; }
        public virtual DbSet<WARN_TEMP_STOCK_INFO> WARN_TEMP_STOCK_INFO { get; set; }
        public virtual DbSet<WCS_TaskProcess> WCS_TaskProcess { get; set; }
        public virtual DbSet<WCS_TaskProcess_D> WCS_TaskProcess_D { get; set; }
        public virtual DbSet<WIP_CL_PARTINFO> WIP_CL_PARTINFO { get; set; }
        public virtual DbSet<WMS_TABLE_RELATION> WMS_TABLE_RELATION { get; set; }
        public virtual DbSet<ALLOCATE_LINE_SN> ALLOCATE_LINE_SN { get; set; }
        public virtual DbSet<ASRS_SHOWINFO> ASRS_SHOWINFO { get; set; }
        public virtual DbSet<BAR_CARTON_D_HIS> BAR_CARTON_D_HIS { get; set; }
        public virtual DbSet<BAR_CARTON_M_HIS> BAR_CARTON_M_HIS { get; set; }
        public virtual DbSet<BAR_PALLET_D_HIS> BAR_PALLET_D_HIS { get; set; }
        public virtual DbSet<BAR_PALLET_M_HIS> BAR_PALLET_M_HIS { get; set; }
        public virtual DbSet<BAR_REPACK_RECORD> BAR_REPACK_RECORD { get; set; }
        public virtual DbSet<BASE_BOM> BASE_BOM { get; set; }
        public virtual DbSet<BASE_CARGOSPACE_CX> BASE_CARGOSPACE_CX { get; set; }
        public virtual DbSet<BASE_CARGOSPACE_TEMP> BASE_CARGOSPACE_TEMP { get; set; }
        public virtual DbSet<BASE_CARGOSPACEBAK> BASE_CARGOSPACEBAK { get; set; }
        public virtual DbSet<BASE_DEPARTMENT_OTYPE> BASE_DEPARTMENT_OTYPE { get; set; }
        public virtual DbSet<BASE_FILEUPLOD> BASE_FILEUPLOD { get; set; }
        public virtual DbSet<BASE_INTERFACELOG_202003> BASE_INTERFACELOG_202003 { get; set; }
        public virtual DbSet<BASE_INTERFACELOG_202004> BASE_INTERFACELOG_202004 { get; set; }
        public virtual DbSet<BASE_LINE_INFO> BASE_LINE_INFO { get; set; }
        public virtual DbSet<BASE_OPERATOR_AREA_BAK> BASE_OPERATOR_AREA_BAK { get; set; }
        public virtual DbSet<BASE_OPERATOR_AREA_NEW> BASE_OPERATOR_AREA_NEW { get; set; }
        public virtual DbSet<Base_PackageScan> Base_PackageScan { get; set; }
        public virtual DbSet<BASE_PART_AREA> BASE_PART_AREA { get; set; }
        public virtual DbSet<BASE_PART_AREA_BACK> BASE_PART_AREA_BACK { get; set; }
        public virtual DbSet<BASE_PART_AREA_CX> BASE_PART_AREA_CX { get; set; }
        public virtual DbSet<BASE_PART_AREA_XX> BASE_PART_AREA_XX { get; set; }
        public virtual DbSet<BASE_PART_HIS> BASE_PART_HIS { get; set; }
        public virtual DbSet<BASE_SENDEMAILPELON> BASE_SENDEMAILPELON { get; set; }
        public virtual DbSet<BaseRGV_TV_PackageNo> BaseRGV_TV_PackageNo { get; set; }
        public virtual DbSet<CHECKERRORMSG> CHECKERRORMSG { get; set; }
        public virtual DbSet<CHECKERRORMSG_APP_BAK> CHECKERRORMSG_APP_BAK { get; set; }
        public virtual DbSet<CMD_AgvTask> CMD_AgvTask { get; set; }
        public virtual DbSet<CMD_LIFT> CMD_LIFT { get; set; }
        public virtual DbSet<CX_FLOW_SWR_INFO> CX_FLOW_SWR_INFO { get; set; }
        public virtual DbSet<DATECODE_STOCK_CURRENT> DATECODE_STOCK_CURRENT { get; set; }
        public virtual DbSet<INTERFACE_LOST_TEMP> INTERFACE_LOST_TEMP { get; set; }
        public virtual DbSet<INTYPE_BAK> INTYPE_BAK { get; set; }
        public virtual DbSet<INTYPEBAK> INTYPEBAK { get; set; }
        public virtual DbSet<LINE_EXCEPT_MO> LINE_EXCEPT_MO { get; set; }
        public virtual DbSet<LOG_SYSERROR> LOG_SYSERROR { get; set; }
        public virtual DbSet<LOG_SYSERROR_APP_BAK> LOG_SYSERROR_APP_BAK { get; set; }
        public virtual DbSet<MO_CINVCODE_FLAG> MO_CINVCODE_FLAG { get; set; }
        public virtual DbSet<MTL_INTERFACE_CACHE> MTL_INTERFACE_CACHE { get; set; }
        public virtual DbSet<OUT_GROUP_D_HIS> OUT_GROUP_D_HIS { get; set; }
        public virtual DbSet<OUT_GROUP_HIS> OUT_GROUP_HIS { get; set; }
        public virtual DbSet<OUT_HANDOVER_HIS> OUT_HANDOVER_HIS { get; set; }
        public virtual DbSet<OUT_PART> OUT_PART { get; set; }
        public virtual DbSet<OUT_TEST> OUT_TEST { get; set; }
        public virtual DbSet<OUT_TEST_D> OUT_TEST_D { get; set; }
        public virtual DbSet<OUTASN_APP_BAK> OUTASN_APP_BAK { get; set; }
        public virtual DbSet<OUTASN_D_APP_BAK> OUTASN_D_APP_BAK { get; set; }
        public virtual DbSet<OUTASN_DBACK> OUTASN_DBACK { get; set; }
        public virtual DbSet<OUTASN2013> OUTASN2013 { get; set; }
        public virtual DbSet<OUTASNBACK> OUTASNBACK { get; set; }
        public virtual DbSet<OUTBILL_D_TEST> OUTBILL_D_TEST { get; set; }
        public virtual DbSet<OUTBILL_TEST> OUTBILL_TEST { get; set; }
        public virtual DbSet<OUTTYPE_BAK> OUTTYPE_BAK { get; set; }
        public virtual DbSet<OUTTYPEBAK> OUTTYPEBAK { get; set; }
        public virtual DbSet<P_InAsnCT_Code> P_InAsnCT_Code { get; set; }
        public virtual DbSet<P_WAREHOUSEID> P_WAREHOUSEID { get; set; }
        public virtual DbSet<PO_GET_CACHE> PO_GET_CACHE { get; set; }
        public virtual DbSet<RCV_INTERFACE_CACHE> RCV_INTERFACE_CACHE { get; set; }
        public virtual DbSet<RETURNTOVENDORPARTLIST> RETURNTOVENDORPARTLIST { get; set; }
        public virtual DbSet<RPT_STOCK_DISCREPENCY_TEST> RPT_STOCK_DISCREPENCY_TEST { get; set; }
        public virtual DbSet<SN_ITEM_HEAD_CONFIG> SN_ITEM_HEAD_CONFIG { get; set; }
        public virtual DbSet<STOCK_ALLO_SCAN_D> STOCK_ALLO_SCAN_D { get; set; }
        public virtual DbSet<STOCK_CHECKEDBILL_HIS> STOCK_CHECKEDBILL_HIS { get; set; }
        public virtual DbSet<STOCK_OCCUPANCY_RELEASE> STOCK_OCCUPANCY_RELEASE { get; set; }
        public virtual DbSet<STOCK_RECHECK_SN> STOCK_RECHECK_SN { get; set; }
        public virtual DbSet<stock_temp> stock_temp { get; set; }
        public virtual DbSet<SYS_LANGUAGE> SYS_LANGUAGE { get; set; }
        public virtual DbSet<SYS_LOG> SYS_LOG { get; set; }
        public virtual DbSet<TASK_INFO> TASK_INFO { get; set; }
        public virtual DbSet<Tb_test> Tb_test { get; set; }
        public virtual DbSet<TEMP_BASE_CARGOSPACE> TEMP_BASE_CARGOSPACE { get; set; }
        public virtual DbSet<TEMP_EBS_RESULT> TEMP_EBS_RESULT { get; set; }
        public virtual DbSet<TEMP_INASSIT_BASE_CARGOSPACE> TEMP_INASSIT_BASE_CARGOSPACE { get; set; }
        public virtual DbSet<TEMP_INBILLTOTALQTY> TEMP_INBILLTOTALQTY { get; set; }
        public virtual DbSet<TEMP_OUTBILL_D_HIS> TEMP_OUTBILL_D_HIS { get; set; }
        public virtual DbSet<TEMP_OUTBILL_D_TEST> TEMP_OUTBILL_D_TEST { get; set; }
        public virtual DbSet<TEMP_OUTBILLTOTALQTY> TEMP_OUTBILLTOTALQTY { get; set; }
        public virtual DbSet<Temp_QueryInOutdetailsReport> Temp_QueryInOutdetailsReport { get; set; }
        public virtual DbSet<Temp_QueryInOutSummaryReport> Temp_QueryInOutSummaryReport { get; set; }
        public virtual DbSet<TEMP_STOCK_CHECKEDBILL_SN> TEMP_STOCK_CHECKEDBILL_SN { get; set; }
        public virtual DbSet<TEMP_STOCK_CURRENT> TEMP_STOCK_CURRENT { get; set; }
        public virtual DbSet<TEMP_STOCK_CURRENT_SN> TEMP_STOCK_CURRENT_SN { get; set; }
        public virtual DbSet<TEMP_STOCK_DURATION> TEMP_STOCK_DURATION { get; set; }
        public virtual DbSet<TEMP_STOCK_DURATION1> TEMP_STOCK_DURATION1 { get; set; }
        public virtual DbSet<TRANSINTEFACEFORASNCHANGE> TRANSINTEFACEFORASNCHANGE { get; set; }
        public virtual DbSet<UserFunction> UserFunction { get; set; }
        public virtual DbSet<V_EBS_TRAN_TEST> V_EBS_TRAN_TEST { get; set; }
        public virtual DbSet<WCSAGVCallBackNotice> WCSAGVCallBackNotice { get; set; }
        public virtual DbSet<WIP_CL_PARTINFO_BAK> WIP_CL_PARTINFO_BAK { get; set; }
        public virtual DbSet<WIPNEGATIVEISSUE_TEMP> WIPNEGATIVEISSUE_TEMP { get; set; }
        public virtual DbSet<WIPRETURNINFO> WIPRETURNINFO { get; set; }
        public virtual DbSet<WRITE_BACK_TIME_SET> WRITE_BACK_TIME_SET { get; set; }
        public virtual DbSet<ZSICT1_USER> ZSICT1_USER { get; set; }
        public virtual DbSet<PDA_V_InAsnList> PDA_V_InAsnList { get; set; }
        public virtual DbSet<PDA_V_InAssitDetails> PDA_V_InAssitDetails { get; set; }
        public virtual DbSet<PDA_V_InAssitScan> PDA_V_InAssitScan { get; set; }
        public virtual DbSet<PDA_V_SNPDStockInfo> PDA_V_SNPDStockInfo { get; set; }
        public virtual DbSet<PDA_V_StockQuery> PDA_V_StockQuery { get; set; }
        public virtual DbSet<PDA_V_StockReset> PDA_V_StockReset { get; set; }
        public virtual DbSet<Stock_Current_Detail_Fun> Stock_Current_Detail_Fun { get; set; }
        public virtual DbSet<stock_current_sn_Fun> stock_current_sn_Fun { get; set; }
        public virtual DbSet<V_ALLOCATE> V_ALLOCATE { get; set; }
        public virtual DbSet<V_ALLOCATE_AUTO> V_ALLOCATE_AUTO { get; set; }
        public virtual DbSet<V_ALLOCATE_DReport> V_ALLOCATE_DReport { get; set; }
        public virtual DbSet<V_ALLOCATE_L> V_ALLOCATE_L { get; set; }
        public virtual DbSet<V_AsrsList> V_AsrsList { get; set; }
        public virtual DbSet<V_AsrsList_New> V_AsrsList_New { get; set; }
        public virtual DbSet<v_bar_carton_m> v_bar_carton_m { get; set; }
        public virtual DbSet<v_bar_pallet_m> v_bar_pallet_m { get; set; }
        public virtual DbSet<v_bar_pallet_m_sn> v_bar_pallet_m_sn { get; set; }
        public virtual DbSet<V_BAR_SN_SPLIT_D_Query> V_BAR_SN_SPLIT_D_Query { get; set; }
        public virtual DbSet<V_BAR_SN_SPLITSQuery> V_BAR_SN_SPLITSQuery { get; set; }
        public virtual DbSet<V_BASE_AREA> V_BASE_AREA { get; set; }
        public virtual DbSet<V_base_bar_sn> V_base_bar_sn { get; set; }
        public virtual DbSet<V_BASE_BAR_SNQuery> V_BASE_BAR_SNQuery { get; set; }
        public virtual DbSet<v_BASE_CARGOSPACE> v_BASE_CARGOSPACE { get; set; }
        public virtual DbSet<V_BASE_CARGOSPACE_L> V_BASE_CARGOSPACE_L { get; set; }
        public virtual DbSet<V_BASE_CARGOSPACE_PK> V_BASE_CARGOSPACE_PK { get; set; }
        public virtual DbSet<V_BASE_CARGOSPACE_SC> V_BASE_CARGOSPACE_SC { get; set; }
        public virtual DbSet<V_BASE_CARGOSPACE_T> V_BASE_CARGOSPACE_T { get; set; }
        public virtual DbSet<v_base_cargospace_temp> v_base_cargospace_temp { get; set; }
        public virtual DbSet<V_BASE_CARGOSPACEListQuery> V_BASE_CARGOSPACEListQuery { get; set; }
        public virtual DbSet<V_BASE_CLIENT> V_BASE_CLIENT { get; set; }
        public virtual DbSet<V_BASE_OPERATOR> V_BASE_OPERATOR { get; set; }
        public virtual DbSet<V_BASE_PART_BOM> V_BASE_PART_BOM { get; set; }
        public virtual DbSet<v_base_part_temp> v_base_part_temp { get; set; }
        public virtual DbSet<V_BASE_VENDOR> V_BASE_VENDOR { get; set; }
        public virtual DbSet<V_BASE_WAREHOUSE> V_BASE_WAREHOUSE { get; set; }
        public virtual DbSet<v_base_warehouse_temp> v_base_warehouse_temp { get; set; }
        public virtual DbSet<V_CARGOSPACE_Report> V_CARGOSPACE_Report { get; set; }
        public virtual DbSet<v_CHAYIReport> v_CHAYIReport { get; set; }
        public virtual DbSet<v_CHAYIReport_Report> v_CHAYIReport_Report { get; set; }
        public virtual DbSet<v_cinvcode_control> v_cinvcode_control { get; set; }
        public virtual DbSet<V_CMD_AgvTask> V_CMD_AgvTask { get; set; }
        public virtual DbSet<V_CMD_MST> V_CMD_MST { get; set; }
        public virtual DbSet<V_CMD_MST_LOG> V_CMD_MST_LOG { get; set; }
        public virtual DbSet<V_CMD_MST_RGV> V_CMD_MST_RGV { get; set; }
        public virtual DbSet<V_DiffTime_Report> V_DiffTime_Report { get; set; }
        public virtual DbSet<v_digitalsignage> v_digitalsignage { get; set; }
        public virtual DbSet<V_EMT_INASNList> V_EMT_INASNList { get; set; }
        public virtual DbSet<V_EMT_INEMTList> V_EMT_INEMTList { get; set; }
        public virtual DbSet<v_gd_minsets> v_gd_minsets { get; set; }
        public virtual DbSet<V_GetInAsn_Ten> V_GetInAsn_Ten { get; set; }
        public virtual DbSet<V_GetPOLine> V_GetPOLine { get; set; }
        public virtual DbSet<V_GetPOList> V_GetPOList { get; set; }
        public virtual DbSet<V_ImportDateList> V_ImportDateList { get; set; }
        public virtual DbSet<V_IN_MERGE_PALLETE> V_IN_MERGE_PALLETE { get; set; }
        public virtual DbSet<V_INASN> V_INASN { get; set; }
        public virtual DbSet<V_Inasn_D> V_Inasn_D { get; set; }
        public virtual DbSet<V_Inasn_D_Edit> V_Inasn_D_Edit { get; set; }
        public virtual DbSet<V_InAsn_PO> V_InAsn_PO { get; set; }
        public virtual DbSet<V_INASN_REPORT> V_INASN_REPORT { get; set; }
        public virtual DbSet<V_InAsnEmt> V_InAsnEmt { get; set; }
        public virtual DbSet<V_INASNSplit> V_INASNSplit { get; set; }
        public virtual DbSet<V_INASSIT_Report> V_INASSIT_Report { get; set; }
        public virtual DbSet<V_InAssitList> V_InAssitList { get; set; }
        public virtual DbSet<V_INBILL> V_INBILL { get; set; }
        public virtual DbSet<V_INBILL_D> V_INBILL_D { get; set; }
        public virtual DbSet<V_INBILL_DAndSN> V_INBILL_DAndSN { get; set; }
        public virtual DbSet<V_INBILL_DSN> V_INBILL_DSN { get; set; }
        public virtual DbSet<V_INBILL_REPORT> V_INBILL_REPORT { get; set; }
        public virtual DbSet<V_InOrOutType> V_InOrOutType { get; set; }
        public virtual DbSet<V_INOutType> V_INOutType { get; set; }
        public virtual DbSet<V_INPO> V_INPO { get; set; }
        public virtual DbSet<V_INPUBOMCOUNT> V_INPUBOMCOUNT { get; set; }
        public virtual DbSet<V_JIANHUO_REPORT> V_JIANHUO_REPORT { get; set; }
        public virtual DbSet<V_Merge_ErpCode_Report_test> V_Merge_ErpCode_Report_test { get; set; }
        public virtual DbSet<V_MixedIngredients> V_MixedIngredients { get; set; }
        public virtual DbSet<v_notuse_positioncode> v_notuse_positioncode { get; set; }
        public virtual DbSet<v_operator_area> v_operator_area { get; set; }
        public virtual DbSet<V_ORA_TEST> V_ORA_TEST { get; set; }
        public virtual DbSet<V_OrderFinish_Stock> V_OrderFinish_Stock { get; set; }
        public virtual DbSet<V_OutAsn_Adj> V_OutAsn_Adj { get; set; }
        public virtual DbSet<V_Outasn_D> V_Outasn_D { get; set; }
        public virtual DbSet<V_OUTASN_D_L> V_OUTASN_D_L { get; set; }
        public virtual DbSet<V_OUTASN_DL> V_OUTASN_DL { get; set; }
        public virtual DbSet<V_OUTASN_REPORT> V_OUTASN_REPORT { get; set; }
        public virtual DbSet<V_OUTASN_SPLIT> V_OUTASN_SPLIT { get; set; }
        public virtual DbSet<V_OUTASNList> V_OUTASNList { get; set; }
        public virtual DbSet<v_outassit_detail> v_outassit_detail { get; set; }
        public virtual DbSet<v_outassit_detail_erp> v_outassit_detail_erp { get; set; }
        public virtual DbSet<V_OUTBILL> V_OUTBILL { get; set; }
        public virtual DbSet<V_OutBill_Adj> V_OutBill_Adj { get; set; }
        public virtual DbSet<v_outbill_detail> v_outbill_detail { get; set; }
        public virtual DbSet<v_outbill_detail_erp> v_outbill_detail_erp { get; set; }
        public virtual DbSet<V_OUTBILL_REPORT> V_OUTBILL_REPORT { get; set; }
        public virtual DbSet<V_OUTBILL_SN> V_OUTBILL_SN { get; set; }
        public virtual DbSet<V_OUTBILLEdit> V_OUTBILLEdit { get; set; }
        public virtual DbSet<V_OUTMIXED_D> V_OUTMIXED_D { get; set; }
        public virtual DbSet<V_OUTMIXED_JF_Detials_D_List> V_OUTMIXED_JF_Detials_D_List { get; set; }
        public virtual DbSet<V_OUTMIXED_JF_Detials_List> V_OUTMIXED_JF_Detials_List { get; set; }
        public virtual DbSet<V_OUTMIXED_JF_List> V_OUTMIXED_JF_List { get; set; }
        public virtual DbSet<V_OutMixedList> V_OutMixedList { get; set; }
        public virtual DbSet<V_OutReturn_In> V_OutReturn_In { get; set; }
        public virtual DbSet<V_PANDIANReport> V_PANDIANReport { get; set; }
        public virtual DbSet<V_PartInfo_BasePart> V_PartInfo_BasePart { get; set; }
        public virtual DbSet<V_PartInfo_InAsn_D> V_PartInfo_InAsn_D { get; set; }
        public virtual DbSet<V_PartInfo_OutAsn_D> V_PartInfo_OutAsn_D { get; set; }
        public virtual DbSet<V_PartInfo_WIP> V_PartInfo_WIP { get; set; }
        public virtual DbSet<V_PartList_ByArea> V_PartList_ByArea { get; set; }
        public virtual DbSet<V_PartList_ByWareHouse> V_PartList_ByWareHouse { get; set; }
        public virtual DbSet<V_PARTUNIONBOM> V_PARTUNIONBOM { get; set; }
        public virtual DbSet<V_PDA_Allocate_D> V_PDA_Allocate_D { get; set; }
        public virtual DbSet<V_PDA_ALLOCATE_EditShow> V_PDA_ALLOCATE_EditShow { get; set; }
        public virtual DbSet<V_PDA_AllocateList> V_PDA_AllocateList { get; set; }
        public virtual DbSet<V_PDA_BASE_CRANECONFIG_DETIALList> V_PDA_BASE_CRANECONFIG_DETIALList { get; set; }
        public virtual DbSet<V_PDA_InAsnEmtList> V_PDA_InAsnEmtList { get; set; }
        public virtual DbSet<V_PDA_Inassit_All> V_PDA_Inassit_All { get; set; }
        public virtual DbSet<V_PDA_InBillRevoke> V_PDA_InBillRevoke { get; set; }
        public virtual DbSet<V_PDA_InEmtList> V_PDA_InEmtList { get; set; }
        public virtual DbSet<V_PDA_INEmtQueryList> V_PDA_INEmtQueryList { get; set; }
        public virtual DbSet<V_PDA_MergeOutAssitList> V_PDA_MergeOutAssitList { get; set; }
        public virtual DbSet<V_PDA_MergeOutBillDeliverList> V_PDA_MergeOutBillDeliverList { get; set; }
        public virtual DbSet<V_PDA_OutAssit_All> V_PDA_OutAssit_All { get; set; }
        public virtual DbSet<V_PDA_OutAssitList> V_PDA_OutAssitList { get; set; }
        public virtual DbSet<V_PDA_OutBill_Items> V_PDA_OutBill_Items { get; set; }
        public virtual DbSet<V_PDA_OutBillDeliverList> V_PDA_OutBillDeliverList { get; set; }
        public virtual DbSet<V_PDA_OutMixed_DList> V_PDA_OutMixed_DList { get; set; }
        public virtual DbSet<V_PDA_OutMixedList> V_PDA_OutMixedList { get; set; }
        public virtual DbSet<V_PDA_QueryINASND> V_PDA_QueryINASND { get; set; }
        public virtual DbSet<V_PDA_QueryINASSIT> V_PDA_QueryINASSIT { get; set; }
        public virtual DbSet<V_PDA_QueryOutASND> V_PDA_QueryOutASND { get; set; }
        public virtual DbSet<V_PDA_QueryOutASSIT> V_PDA_QueryOutASSIT { get; set; }
        public virtual DbSet<V_PDA_QueryOutBill> V_PDA_QueryOutBill { get; set; }
        public virtual DbSet<V_PDA_QueryTEMP_InBill_D> V_PDA_QueryTEMP_InBill_D { get; set; }
        public virtual DbSet<V_PDA_QueryTEMP_OutBill_D> V_PDA_QueryTEMP_OutBill_D { get; set; }
        public virtual DbSet<V_PDA_STOCK_ALLO_SCAN_D> V_PDA_STOCK_ALLO_SCAN_D { get; set; }
        public virtual DbSet<V_PDA_TemporaryAlloList> V_PDA_TemporaryAlloList { get; set; }
        public virtual DbSet<V_PDA_TemporaryInItems> V_PDA_TemporaryInItems { get; set; }
        public virtual DbSet<V_PDA_TemporaryInList> V_PDA_TemporaryInList { get; set; }
        public virtual DbSet<V_PDA_TemporaryOutItems> V_PDA_TemporaryOutItems { get; set; }
        public virtual DbSet<V_PDA_TemporaryOutList> V_PDA_TemporaryOutList { get; set; }
        public virtual DbSet<V_QueryINPO> V_QueryINPO { get; set; }
        public virtual DbSet<V_QuickMIXED> V_QuickMIXED { get; set; }
        public virtual DbSet<v_rational_issue> v_rational_issue { get; set; }
        public virtual DbSet<V_RD_INASSITListQuery> V_RD_INASSITListQuery { get; set; }
        public virtual DbSet<V_ScanInAllocateInfo> V_ScanInAllocateInfo { get; set; }
        public virtual DbSet<V_ScanInAssitInfo> V_ScanInAssitInfo { get; set; }
        public virtual DbSet<V_Seral_Details> V_Seral_Details { get; set; }
        public virtual DbSet<V_SerialNumberInfo> V_SerialNumberInfo { get; set; }
        public virtual DbSet<V_ShowSN_IN> V_ShowSN_IN { get; set; }
        public virtual DbSet<V_ShowSN_Stock> V_ShowSN_Stock { get; set; }
        public virtual DbSet<v_ShowSNSplit> v_ShowSNSplit { get; set; }
        public virtual DbSet<V_sn_item_head_config> V_sn_item_head_config { get; set; }
        public virtual DbSet<V_Stock_Base_Cargospace> V_Stock_Base_Cargospace { get; set; }
        public virtual DbSet<V_STOCK_BILLList> V_STOCK_BILLList { get; set; }
        public virtual DbSet<v_stock_checkbill_d> v_stock_checkbill_d { get; set; }
        public virtual DbSet<v_STOCK_CHECKBILL_List> v_STOCK_CHECKBILL_List { get; set; }
        public virtual DbSet<V_STOCK_CHECKBILLList> V_STOCK_CHECKBILLList { get; set; }
        public virtual DbSet<V_STOCK_CHECKDBILL> V_STOCK_CHECKDBILL { get; set; }
        public virtual DbSet<V_Stock_CheckDiffSearch> V_Stock_CheckDiffSearch { get; set; }
        public virtual DbSet<v_stock_checkedbill> v_stock_checkedbill { get; set; }
        public virtual DbSet<V_STOCK_CHECKEDBILL_CY> V_STOCK_CHECKEDBILL_CY { get; set; }
        public virtual DbSet<V_STOCK_CHECKEDBILL_LIST> V_STOCK_CHECKEDBILL_LIST { get; set; }
        public virtual DbSet<V_STOCK_CURRENT> V_STOCK_CURRENT { get; set; }
        public virtual DbSet<v_stock_current_adjust_d> v_stock_current_adjust_d { get; set; }
        public virtual DbSet<V_STOCK_Current_ALL> V_STOCK_Current_ALL { get; set; }
        public virtual DbSet<V_STOCK_CURRENT_List> V_STOCK_CURRENT_List { get; set; }
        public virtual DbSet<V_Stock_DataCode_Edit> V_Stock_DataCode_Edit { get; set; }
        public virtual DbSet<V_Stock_DateCode> V_Stock_DateCode { get; set; }
        public virtual DbSet<V_STOCK_ElectBinCard> V_STOCK_ElectBinCard { get; set; }
        public virtual DbSet<V_STOCK_FORERP> V_STOCK_FORERP { get; set; }
        public virtual DbSet<V_STOCK_OCCUPY> V_STOCK_OCCUPY { get; set; }
        public virtual DbSet<V_STOCK_POSTITON> V_STOCK_POSTITON { get; set; }
        public virtual DbSet<V_StockDiffTime_Report> V_StockDiffTime_Report { get; set; }
        public virtual DbSet<V_SUM_STOCKCURRENT> V_SUM_STOCKCURRENT { get; set; }
        public virtual DbSet<V_SYS_CONFIG> V_SYS_CONFIG { get; set; }
        public virtual DbSet<V_SYS_LOG> V_SYS_LOG { get; set; }
        public virtual DbSet<V_SYS_PARAMETER> V_SYS_PARAMETER { get; set; }
        public virtual DbSet<V_SystemLog> V_SystemLog { get; set; }
        public virtual DbSet<v_temp_area_paet_warehouse> v_temp_area_paet_warehouse { get; set; }
        public virtual DbSet<v_temp_base_area> v_temp_base_area { get; set; }
        public virtual DbSet<v_temp_base_client> v_temp_base_client { get; set; }
        public virtual DbSet<v_temp_base_stock_current> v_temp_base_stock_current { get; set; }
        public virtual DbSet<v_temp_base_vendor> v_temp_base_vendor { get; set; }
        public virtual DbSet<V_TEMP_IN_MO_INFO> V_TEMP_IN_MO_INFO { get; set; }
        public virtual DbSet<v_temp_outbill_d_cin_t> v_temp_outbill_d_cin_t { get; set; }
        public virtual DbSet<v_temp_outbill_d_cin_t_erpcode> v_temp_outbill_d_cin_t_erpcode { get; set; }
        public virtual DbSet<V_TemporaryAreaCinv_Report> V_TemporaryAreaCinv_Report { get; set; }
        public virtual DbSet<V_TRADETYPE> V_TRADETYPE { get; set; }
        public virtual DbSet<V_WARNINGSTOCK_REPORT> V_WARNINGSTOCK_REPORT { get; set; }
        public virtual DbSet<V_WCS_TaskProcess> V_WCS_TaskProcess { get; set; }
        public virtual DbSet<V_WmsAndEbsQtyDiffReport> V_WmsAndEbsQtyDiffReport { get; set; }
        public virtual DbSet<view_get_firstdatecode> view_get_firstdatecode { get; set; }
        public virtual DbSet<view_get_handover_check> view_get_handover_check { get; set; }
        public virtual DbSet<view_get_palorcar_type> view_get_palorcar_type { get; set; }
        public virtual DbSet<view_get_part_norecode> view_get_part_norecode { get; set; }
        public virtual DbSet<view_get_sn_locklist> view_get_sn_locklist { get; set; }
        public virtual DbSet<view_get_snlist_report> view_get_snlist_report { get; set; }
        public virtual DbSet<view_get_stock_datecodenum> view_get_stock_datecodenum { get; set; }
        public virtual DbSet<view_inbill_snreport> view_inbill_snreport { get; set; }
        public virtual DbSet<view_inventory_turnin> view_inventory_turnin { get; set; }
        public virtual DbSet<view_outbill_snreport> view_outbill_snreport { get; set; }
        public virtual DbSet<View_OUTBILLEdit> View_OUTBILLEdit { get; set; }
        public virtual DbSet<view_position_nostocklist_line> view_position_nostocklist_line { get; set; }
        public virtual DbSet<view_position_stock_line> view_position_stock_line { get; set; }
        public virtual DbSet<view_position_stock_ratio> view_position_stock_ratio { get; set; }
        public virtual DbSet<view_STOCK_CHECKBILL_D> view_STOCK_CHECKBILL_D { get; set; }
        public virtual DbSet<view_stock_checkdiff> view_stock_checkdiff { get; set; }
        public virtual DbSet<view_stock_current> view_stock_current { get; set; }
        public virtual DbSet<view_transaction_sn> view_transaction_sn { get; set; }
    
        [DbFunction("XUELONGEntities", "Fun_CheckCinvBarCode")]
        public virtual IQueryable<Fun_CheckCinvBarCode_Result> Fun_CheckCinvBarCode(string scanCinv)
        {
            var scanCinvParameter = scanCinv != null ?
                new ObjectParameter("ScanCinv", scanCinv) :
                new ObjectParameter("ScanCinv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_CheckCinvBarCode_Result>("[XUELONGEntities].[Fun_CheckCinvBarCode](@ScanCinv)", scanCinvParameter);
        }
    
        [DbFunction("XUELONGEntities", "Fun_CheckCinvBarCodeEXP")]
        public virtual IQueryable<Fun_CheckCinvBarCodeEXP_Result> Fun_CheckCinvBarCodeEXP(string scanCinv, string sncode, string isTemparea)
        {
            var scanCinvParameter = scanCinv != null ?
                new ObjectParameter("ScanCinv", scanCinv) :
                new ObjectParameter("ScanCinv", typeof(string));
    
            var sncodeParameter = sncode != null ?
                new ObjectParameter("sncode", sncode) :
                new ObjectParameter("sncode", typeof(string));
    
            var isTempareaParameter = isTemparea != null ?
                new ObjectParameter("isTemparea", isTemparea) :
                new ObjectParameter("isTemparea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_CheckCinvBarCodeEXP_Result>("[XUELONGEntities].[Fun_CheckCinvBarCodeEXP](@ScanCinv, @sncode, @isTemparea)", scanCinvParameter, sncodeParameter, isTempareaParameter);
        }
    
        [DbFunction("XUELONGEntities", "Fun_CheckSJJAGVSite")]
        public virtual IQueryable<Fun_CheckSJJAGVSite_Result> Fun_CheckSJJAGVSite(string p_SiteCode, Nullable<int> p_SJJTYPE)
        {
            var p_SiteCodeParameter = p_SiteCode != null ?
                new ObjectParameter("P_SiteCode", p_SiteCode) :
                new ObjectParameter("P_SiteCode", typeof(string));
    
            var p_SJJTYPEParameter = p_SJJTYPE.HasValue ?
                new ObjectParameter("P_SJJTYPE", p_SJJTYPE) :
                new ObjectParameter("P_SJJTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_CheckSJJAGVSite_Result>("[XUELONGEntities].[Fun_CheckSJJAGVSite](@P_SiteCode, @P_SJJTYPE)", p_SiteCodeParameter, p_SJJTYPEParameter);
        }
    
        [DbFunction("XUELONGEntities", "Fun_ConvertDateCodeByFormat")]
        public virtual IQueryable<Fun_ConvertDateCodeByFormat_Result> Fun_ConvertDateCodeByFormat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_ConvertDateCodeByFormat_Result>("[XUELONGEntities].[Fun_ConvertDateCodeByFormat]()");
        }
    
        [DbFunction("XUELONGEntities", "Fun_GetInfoFromBarCode")]
        public virtual IQueryable<Fun_GetInfoFromBarCode_Result> Fun_GetInfoFromBarCode(string p_SN)
        {
            var p_SNParameter = p_SN != null ?
                new ObjectParameter("P_SN", p_SN) :
                new ObjectParameter("P_SN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_GetInfoFromBarCode_Result>("[XUELONGEntities].[Fun_GetInfoFromBarCode](@P_SN)", p_SNParameter);
        }
    
        [DbFunction("XUELONGEntities", "Fun_GetLineWorkReport")]
        public virtual IQueryable<Fun_GetLineWorkReport_Result> Fun_GetLineWorkReport(string p_Date, string p_Line)
        {
            var p_DateParameter = p_Date != null ?
                new ObjectParameter("P_Date", p_Date) :
                new ObjectParameter("P_Date", typeof(string));
    
            var p_LineParameter = p_Line != null ?
                new ObjectParameter("P_Line", p_Line) :
                new ObjectParameter("P_Line", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_GetLineWorkReport_Result>("[XUELONGEntities].[Fun_GetLineWorkReport](@P_Date, @P_Line)", p_DateParameter, p_LineParameter);
        }
    
        [DbFunction("XUELONGEntities", "fun_TestApply")]
        public virtual IQueryable<fun_TestApply_Result> fun_TestApply(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun_TestApply_Result>("[XUELONGEntities].[fun_TestApply](@id)", idParameter);
        }
    
        [DbFunction("XUELONGEntities", "GetCticketCode")]
        public virtual IQueryable<GetCticketCode_Result> GetCticketCode(string p_CticketCode)
        {
            var p_CticketCodeParameter = p_CticketCode != null ?
                new ObjectParameter("P_CticketCode", p_CticketCode) :
                new ObjectParameter("P_CticketCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetCticketCode_Result>("[XUELONGEntities].[GetCticketCode](@P_CticketCode)", p_CticketCodeParameter);
        }
    
        [DbFunction("XUELONGEntities", "IsHASPalletCodeInASN")]
        public virtual IQueryable<IsHASPalletCodeInASN_Result> IsHASPalletCodeInASN(string p_PalletCode, string p_INAsnID)
        {
            var p_PalletCodeParameter = p_PalletCode != null ?
                new ObjectParameter("P_PalletCode", p_PalletCode) :
                new ObjectParameter("P_PalletCode", typeof(string));
    
            var p_INAsnIDParameter = p_INAsnID != null ?
                new ObjectParameter("P_INAsnID", p_INAsnID) :
                new ObjectParameter("P_INAsnID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<IsHASPalletCodeInASN_Result>("[XUELONGEntities].[IsHASPalletCodeInASN](@P_PalletCode, @P_INAsnID)", p_PalletCodeParameter, p_INAsnIDParameter);
        }
    
        [DbFunction("XUELONGEntities", "StrToTable")]
        public virtual IQueryable<StrToTable_Result> StrToTable(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<StrToTable_Result>("[XUELONGEntities].[StrToTable](@str)", strParameter);
        }
    }
}
