//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_TRANSPORTATIONPLAN
    {
        public string id { get; set; }
        public string docno { get; set; }
        public string customeraddr { get; set; }
        public string currency { get; set; }
        public string transtype { get; set; }
        public string palletcode { get; set; }
        public string cerpcode { get; set; }
        public string cerpcodeline { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string customerno { get; set; }
        public string cvendercode { get; set; }
        public string cvender { get; set; }
        public Nullable<System.DateTime> reqdeliverydate { get; set; }
        public Nullable<System.DateTime> pladeliverydate { get; set; }
        public string memo { get; set; }
        public Nullable<int> updatemark { get; set; }
        public Nullable<System.DateTime> wmsupdatetime { get; set; }
        public Nullable<System.DateTime> oaupdatetime { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public Nullable<System.DateTime> PRODUCETIME { get; set; }
        public Nullable<int> ISSIGN { get; set; }
        public string SINGNOWNER { get; set; }
        public Nullable<System.DateTime> SINGTIME { get; set; }
        public int SNType { get; set; }
        public int PackSNType { get; set; }
    }
}
