//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_GROUP_D
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual OUT_GROUP OUT_GROUP { get; set; }
    }
}
