//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_HANDOVER_CHECK
    {
        public string id { get; set; }
        public string cerpcode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iqty { get; set; }
        public Nullable<decimal> qty_demand { get; set; }
        public Nullable<decimal> qty_out { get; set; }
        public Nullable<decimal> qty_handover { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<decimal> cstatus { get; set; }
        public string sncode { get; set; }
    }
}
