//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTASN
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditpersoncode { get; set; }
        public Nullable<System.DateTime> dauditdate { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string cerpcode { get; set; }
        public string cmemo { get; set; }
        public string cso { get; set; }
        public decimal itype { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cclientcode { get; set; }
        public string cclient { get; set; }
        public string out_vendor { get; set; }
        public Nullable<decimal> is_merge { get; set; }
        public string fg_cinvcode { get; set; }
        public string merge_id { get; set; }
        public string site { get; set; }
        public Nullable<decimal> is_smt { get; set; }
        public string class_code { get; set; }
        public Nullable<decimal> is_semi { get; set; }
        public Nullable<decimal> special_out { get; set; }
        public Nullable<decimal> critical_part { get; set; }
        public Nullable<decimal> fg_qty { get; set; }
        public Nullable<decimal> is_assiting { get; set; }
        public Nullable<decimal> is_whole { get; set; }
        public string reasoncode { get; set; }
        public string worktype { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string HYNum { get; set; }
        public string wo { get; set; }
    }
}
