//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTASN_D_SPLIT
    {
        public string Id { get; set; }
        public string Outasn_Id { get; set; }
        public string Outasn_D_Ids { get; set; }
        public string CinvCode { get; set; }
        public string Flag { get; set; }
        public Nullable<decimal> OldQty { get; set; }
        public Nullable<decimal> CjQty { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
