//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTBILL_D
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cstatus { get; set; }
        public decimal iquantity { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvbarcode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cerpcodeline { get; set; }
        public Nullable<System.DateTime> doutdate { get; set; }
        public string coutpersoncode { get; set; }
        public string cmemo { get; set; }
        public Nullable<decimal> ioutasnline { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public string ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public string allocate_d_ids { get; set; }
        public Nullable<decimal> allotype { get; set; }
        public string asn_d_ids { get; set; }
        public Nullable<decimal> part_bond { get; set; }
        public Nullable<decimal> asrs_status { get; set; }
        public Nullable<decimal> wmstskid { get; set; }
        public Nullable<decimal> asrs_num { get; set; }
        public string pallet_code { get; set; }
        public Nullable<decimal> isgoback { get; set; }
        public string cstoppositioncode { get; set; }
        public string cnewpositioncode { get; set; }
        public string callocateid { get; set; }
        public Nullable<int> lineid { get; set; }
        public Nullable<int> outasndlineid { get; set; }
        public string wire { get; set; }
        public string sourcecode { get; set; }
        public string wo { get; set; }
    }
}
