//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTMIXED
    {
        public string ID { get; set; }
        public string MIXEDCODE { get; set; }
        public string ERPCODE { get; set; }
        public string OUTCTICKETCODE { get; set; }
        public string CINVBARCODE { get; set; }
        public decimal OTYPE { get; set; }
        public string CSTATUS { get; set; }
        public string STARTSITE { get; set; }
        public string ENDSITE { get; set; }
        public string CREATERUSER { get; set; }
        public Nullable<System.DateTime> CREATERTIME { get; set; }
        public string MODIFYUSER { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string CDEFIEND1 { get; set; }
        public string CDEFIEND2 { get; set; }
        public string CDEFIEND3 { get; set; }
        public string REMARK { get; set; }
        public string MIXEDSITE { get; set; }
    }
}
