//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTORDER_D
    {
        public string ids { get; set; }
        public string id { get; set; }
        public int OrderLine { get; set; }
        public string CinvCode { get; set; }
        public string CinvName { get; set; }
        public Nullable<decimal> Iquantity { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Define1 { get; set; }
        public string Define2 { get; set; }
        public string Define3 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateOwner { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateOwner { get; set; }
        public Nullable<decimal> FinishQty { get; set; }
    }
}
