//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTORDER
    {
        public string id { get; set; }
        public string OrderNo { get; set; }
        public string CustomOrderNo { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustomId { get; set; }
        public string CustomName { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> AfterTaxAmount { get; set; }
        public string DeliveryAddress { get; set; }
        public string SalesMan { get; set; }
        public Nullable<int> OrderSource { get; set; }
        public Nullable<int> Status { get; set; }
        public string Memo { get; set; }
        public string Define1 { get; set; }
        public string Define2 { get; set; }
        public string Define3 { get; set; }
        public Nullable<System.DateTime> Define4 { get; set; }
        public Nullable<decimal> Define5 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateOwner { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateOwner { get; set; }
    }
}
