//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_V_StockReset
    {
        public string ids { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> sn_qty { get; set; }
        public string sntype { get; set; }
        public Nullable<decimal> typecode { get; set; }
        public string weeks { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string userno { get; set; }
    }
}
