//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_V_InAsnList
    {
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public Nullable<decimal> INUM { get; set; }
        public decimal YJNUM { get; set; }
        public Nullable<decimal> SYNUM { get; set; }
        public string cticketcode { get; set; }
    }
}
