//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_V_InAssitDetails
    {
        public string cticketcode { get; set; }
        public string asncticketcode { get; set; }
        public string OCRITICAL_PART { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public decimal inum { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public decimal YJNUM { get; set; }
        public Nullable<decimal> SYNUM { get; set; }
        public string caccountid { get; set; }
        public string cstatus { get; set; }
    }
}
