//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_V_StockQuery
    {
        public string id { get; set; }
        public string CWAREHOUSECODE { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CINVCODE { get; set; }
        public Nullable<decimal> IQTY { get; set; }
        public string CALIAS { get; set; }
        public string SN { get; set; }
    }
}
