//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_GET_CACHE
    {
        public string receipt_num { get; set; }
        public Nullable<System.DateTime> get_date { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cerpcodeline { get; set; }
        public string cpo { get; set; }
        public Nullable<decimal> ipoline { get; set; }
        public string erpcodelinenum { get; set; }
        public string po_numbername { get; set; }
        public string po_linenumbername { get; set; }
    }
}
