//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_FUN_RETURN_INFO
    {
        public string fun_proc_name { get; set; }
        public decimal sequence { get; set; }
        public string info_code { get; set; }
        public string info_result { get; set; }
        public string info_msg { get; set; }
        public string memo { get; set; }
    }
}
