//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_PART_MORE_SPACE
    {
        public string id { get; set; }
        public string warehouse { get; set; }
        public string cpositioncode { get; set; }
        public string cpositionname { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iqty { get; set; }
        public Nullable<decimal> remainspace { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
    }
}
