//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder_M()
        {
            this.SalesOrder_D = new HashSet<SalesOrder_D>();
        }
    
        public string ID { get; set; }
        public string SalesOrderNo { get; set; }
        public string CustomerId { get; set; }
        public System.DateTime RequestShipDate { get; set; }
        public int Status { get; set; }
        public string CreateOwer { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastUpdOwner { get; set; }
        public Nullable<System.DateTime> LastUpdTime { get; set; }
        public string LastCancelOwner { get; set; }
        public Nullable<System.DateTime> LastCancelTime { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder_D> SalesOrder_D { get; set; }
    }
}
