//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder_D
    {
        public string IDS { get; set; }
        public string ID { get; set; }
        public string PartNo { get; set; }
        public decimal ShipQty { get; set; }
        public decimal Price { get; set; }
        public System.DateTime RequestShipDate { get; set; }
        public string CreateOwer { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastUpdOwner { get; set; }
        public Nullable<System.DateTime> LastUpdTime { get; set; }
    
        public virtual SalesOrder_M SalesOrder_M { get; set; }
    }
}
