//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnResetOperateInfo
    {
        public string id { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string lockuser { get; set; }
        public Nullable<System.DateTime> locktime { get; set; }
        public string unlockuser { get; set; }
        public Nullable<System.DateTime> unlocktime { get; set; }
        public string inasncode { get; set; }
        public Nullable<int> is_diff { get; set; }
        public Nullable<int> cstatus { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
    }
}
