//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSX_Site_Monitor
    {
        public string id { get; set; }
        public string lineid { get; set; }
        public string siteid { get; set; }
        public string palletcode { get; set; }
        public string plc { get; set; }
        public System.DateTime monitortime { get; set; }
        public string remark { get; set; }
    }
}
