//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_SN_LOCK
    {
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string positioncode { get; set; }
        public string positionname { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> snqty { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public Nullable<System.DateTime> locktime { get; set; }
        public Nullable<System.DateTime> unlocktime { get; set; }
        public Nullable<decimal> cstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public Nullable<decimal> cenable { get; set; }
    }
}
