//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_DEDUCT_SN_DETAIL
    {
        public string id { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> create_times { get; set; }
        public string create_owner { get; set; }
        public string cticketcode { get; set; }
        public string sn_id { get; set; }
        public string sncode { get; set; }
        public string deduct_position { get; set; }
        public string cinvcode { get; set; }
        public string cpositioncode { get; set; }
        public string ctopositioncode { get; set; }
        public Nullable<decimal> begin_qty { get; set; }
        public Nullable<decimal> trans_qty { get; set; }
        public Nullable<decimal> final_qty { get; set; }
        public string proc_name { get; set; }
        public string memo { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
    }
}
