//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_ALLO_SCAN_D
    {
        public string id { get; set; }
        public string allo_ids { get; set; }
        public string allo_id { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string ctopositioncode { get; set; }
        public string ctoposition { get; set; }
        public string csn { get; set; }
        public Nullable<decimal> cdatecode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public System.DateTime dindate { get; set; }
        public string cinpersoncode { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string RULECODE { get; set; }
    }
}
