//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_OCCUPANCY_RELEASE
    {
        public string item_id { get; set; }
        public string storage { get; set; }
        public Nullable<decimal> totalnum { get; set; }
        public string cticketcode { get; set; }
        public string flag { get; set; }
        public string id { get; set; }
        public string billid { get; set; }
        public Nullable<System.DateTime> opttime { get; set; }
        public Nullable<decimal> type { get; set; }
        public string asn_id { get; set; }
    }
}
