//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CURRENT_SN
    {
        public string ids { get; set; }
        public string stock_id { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateuser { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string furnaceno { get; set; }
        public string memo { get; set; }
        public string default2 { get; set; }
        public string stocktype { get; set; }
        public string SN_CODE20 { get; set; }
        public string palletcode { get; set; }
        public string ERPCODE { get; set; }
        public string VENDORCODE { get; set; }
        public string RULECODE { get; set; }
    }
}
