//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_ADJUST
    {
        public string ID { get; set; }
        public string CCREATEOWNERCODE { get; set; }
        public Nullable<System.DateTime> DCREATETIME { get; set; }
        public string CAUDITPERSON { get; set; }
        public Nullable<System.DateTime> DAUDITTIME { get; set; }
        public string CTICKETCODE { get; set; }
        public string CSTATUS { get; set; }
        public System.DateTime DINDATE { get; set; }
        public string CMEMO { get; set; }
        public string CERPCODE { get; set; }
        public Nullable<System.DateTime> DDEFINE3 { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public Nullable<System.DateTime> DDEFINE4 { get; set; }
        public Nullable<decimal> IDEFINE5 { get; set; }
        public int ATYPE { get; set; }
    }
}
