//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CURRENT_SN_RESET
    {
        public string id { get; set; }
        public string stock_id { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public string cmemo { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string groupid { get; set; }
        public string cinvcode { get; set; }
        public string cpositioncode { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> grouptime { get; set; }
    }
}
