//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CHECKBILL
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string cauditperson { get; set; }
        public Nullable<System.DateTime> daudittime { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string cerpcode { get; set; }
        public string cmemo { get; set; }
        public System.DateTime dcheckdate { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string checktype { get; set; }
        public Nullable<System.DateTime> dcirclecheckbegindate { get; set; }
        public Nullable<System.DateTime> dcirclecheckenddate { get; set; }
        public string ccheckname { get; set; }
        public Nullable<decimal> max_part_ium { get; set; }
        public Nullable<decimal> isadjust { get; set; }
        public string planname { get; set; }
        public string statusf { get; set; }
        public string worktype { get; set; }
        public string lineid { get; set; }
        public string isLXCheck { get; set; }
    }
}
