//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CHECK_PLAN
    {
        public string id { get; set; }
        public string planid { get; set; }
        public string plan_name { get; set; }
        public string plan_describe { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> freeze_date { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string last_upd_owner { get; set; }
        public Nullable<System.DateTime> last_upd_time { get; set; }
        public Nullable<decimal> flag { get; set; }
    }
}
