//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_CURRENT_PalletCode
    {
        public string ID { get; set; }
        public string Cinvcode { get; set; }
        public string CinvName { get; set; }
        public Nullable<decimal> iQuantity { get; set; }
        public string PalletCode { get; set; }
        public Nullable<int> iType { get; set; }
        public string AGVSiteCode { get; set; }
        public string AGVSiteName { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public string dCreateOwner { get; set; }
    }
}
