//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CURRENT_BN
    {
        public string ids { get; set; }
        public string SNIDS { get; set; }
        public string BNCODE { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateuser { get; set; }
        public string cdefined1 { get; set; }
        public string cdefined2 { get; set; }
        public string memo { get; set; }
    }
}
