//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_RECHECK_SN
    {
        public string ID { get; set; }
        public string SN { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CPOSITIONNAME { get; set; }
        public Nullable<int> CHECKNUM { get; set; }
        public Nullable<int> CHECKDAYS1 { get; set; }
        public Nullable<int> CHECKDAYS1RESULT { get; set; }
        public string CHECKDAYS1USER { get; set; }
        public Nullable<System.DateTime> CHECKDAYS1DATE { get; set; }
        public string CDEFIND1 { get; set; }
        public string CDEFIND2 { get; set; }
        public string CDEFIND3 { get; set; }
        public string CDEFIND4 { get; set; }
        public string CMEMO { get; set; }
        public string CCREATEOWNERCODE { get; set; }
        public Nullable<System.DateTime> DCREATETIME { get; set; }
        public string CLASTUPDATEDOWNERCODE { get; set; }
        public Nullable<System.DateTime> DLASTUPDATEDTIME { get; set; }
    }
}
