//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CURRENT_ADJUST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_CURRENT_ADJUST()
        {
            this.STOCK_CURRENT_ADJUST_D = new HashSet<STOCK_CURRENT_ADJUST_D>();
        }
    
        public string id { get; set; }
        public string cticketcode { get; set; }
        public string reason { get; set; }
        public string cstatus { get; set; }
        public string createowner { get; set; }
        public System.DateTime createtime { get; set; }
        public string reviewuser { get; set; }
        public Nullable<System.DateTime> reviewtime { get; set; }
        public string lastupdateuser { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_CURRENT_ADJUST_D> STOCK_CURRENT_ADJUST_D { get; set; }
    }
}
