//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PARAMETERGROUP
    {
        public string ID { get; set; }
        public string FLAG_TYPE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string REMARK { get; set; }
        public string CREATEUSER { get; set; }
    }
}
