//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_STOCKDIFF_LOG
    {
        public string id { get; set; }
        public string caseid { get; set; }
        public string caseno { get; set; }
        public string casetype { get; set; }
        public string partcode { get; set; }
        public string positioncode { get; set; }
        public string bf_sn_qty { get; set; }
        public string bf_stock_qty { get; set; }
        public string bfeforeres { get; set; }
        public string af_sn_qty { get; set; }
        public string af_stock_qty { get; set; }
        public string afterres { get; set; }
        public string userno { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
