//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Job
    {
        public string id { get; set; }
        public string jobname { get; set; }
        public string dllname { get; set; }
        public string classname { get; set; }
        public string functionname { get; set; }
        public int dayfretype { get; set; }
        public string oncedayfre { get; set; }
        public Nullable<int> splittime { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> beginruntime { get; set; }
        public Nullable<System.DateTime> lastendtime { get; set; }
        public int cstatus { get; set; }
    }
}
