//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SCANINLOG
    {
        public string ID { get; set; }
        public string GROUPID { get; set; }
        public Nullable<int> STEP { get; set; }
        public string LineId { get; set; }
        public string SiteId { get; set; }
        public string PalletCode { get; set; }
        public string MSG { get; set; }
        public string REMARK { get; set; }
        public string CDEFINED1 { get; set; }
        public string CDEFINED2 { get; set; }
        public string CDEFINED3 { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
    }
}
