//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIG
    {
        public string id { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string config_desc { get; set; }
        public string config_value { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string type_memo { get; set; }
        public Nullable<decimal> status { get; set; }
    }
}
