//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PARAMETER
    {
        public string flag_id { get; set; }
        public string flag_name { get; set; }
        public string flag_type { get; set; }
        public Nullable<decimal> sortid { get; set; }
        public string memo { get; set; }
        public string ID { get; set; }
    }
}
