//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ModuleFormInstance
    {
        public string F_Id { get; set; }
        public string F_FormId { get; set; }
        public string F_ObjectId { get; set; }
        public string F_InstanceJson { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
    }
}
