//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_INFO
    {
        public string id { get; set; }
        public string cticketcode { get; set; }
        public string assignfromid { get; set; }
        public string assignfromname { get; set; }
        public string assigntoid { get; set; }
        public string assigntoname { get; set; }
        public System.DateTime assigndate { get; set; }
        public Nullable<System.DateTime> expectdate { get; set; }
        public Nullable<System.DateTime> actualdate { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<decimal> exelevel { get; set; }
        public Nullable<decimal> status { get; set; }
        public string jobcontexts { get; set; }
        public string contexts { get; set; }
        public string ccreateownercode { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string cmodifiedownercode { get; set; }
        public Nullable<System.DateTime> dmodifiedtime { get; set; }
    }
}
