//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEST_FLOAT
    {
        public string id { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> num { get; set; }
        public string remark { get; set; }
    }
}
