//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_IN_MO_INFO
    {
        public string id { get; set; }
        public string wo { get; set; }
        public string wo_qty { get; set; }
        public string start_date { get; set; }
        public string create_time { get; set; }
        public string create_owner { get; set; }
        public string last_upd_time { get; set; }
        public string last_upd_owner { get; set; }
        public string shift { get; set; }
        public string linebody { get; set; }
        public string side { get; set; }
        public string special { get; set; }
        public string departmentno { get; set; }
        public string iscountjobtime { get; set; }
        public string onlinetime { get; set; }
        public string sec_cinvcode { get; set; }
        public string issave { get; set; }
        public string models { get; set; }
    }
}
