//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_BASE_AREA
    {
        public string ID { get; set; }
        public string AREANAME { get; set; }
        public string BACKUPCPOSITIONCODE { get; set; }
        public string BACKUPCPOSITION { get; set; }
        public string FLAG { get; set; }
        public Nullable<int> issave { get; set; }
    }
}
