//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_BASE_LINE_LIST
    {
        public string ID { get; set; }
        public Nullable<int> ERROR_FLAG { get; set; }
        public string LINEID { get; set; }
    }
}
