//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_STOCK_CHECKEDBILL_SN
    {
        public string ids { get; set; }
        public string stock_checkbill_d_ids { get; set; }
        public string checktype { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createuser { get; set; }
    }
}
