//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_TVShowInfo
    {
        public string ID { get; set; }
        public string LineName { get; set; }
        public string SiteName { get; set; }
        public string pallatCodeCount { get; set; }
        public string ERPCode { get; set; }
        public string OutBillCode { get; set; }
        public string PositionCode_out { get; set; }
        public string pallatCode { get; set; }
        public string WL1_out { get; set; }
        public Nullable<decimal> OutBillQty1 { get; set; }
        public Nullable<decimal> OutJHQty1 { get; set; }
        public Nullable<decimal> OutFKQty1 { get; set; }
        public string WL2_out { get; set; }
        public Nullable<decimal> OutBillQty2 { get; set; }
        public Nullable<decimal> OutJHQty2 { get; set; }
        public Nullable<decimal> OutFKQty2 { get; set; }
        public string WL3_out { get; set; }
        public Nullable<decimal> OutBillQty3 { get; set; }
        public Nullable<decimal> OutJHQty3 { get; set; }
        public Nullable<decimal> OutFKQty3 { get; set; }
        public string WL4_out { get; set; }
        public Nullable<decimal> OutBillQty4 { get; set; }
        public Nullable<decimal> OutJHQty4 { get; set; }
        public Nullable<decimal> OutFKQty4 { get; set; }
        public string OutFB { get; set; }
        public string Message { get; set; }
        public string Status_out { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
