//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_OUTMIXED_D
    {
        public string id { get; set; }
        public string outasncticketcode { get; set; }
        public string outbillcticketcode { get; set; }
        public string outbilldids { get; set; }
        public string CERPCODE { get; set; }
        public string cstatus { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public decimal iquantity { get; set; }
        public string cinvbarcode { get; set; }
        public string cerpcodeline { get; set; }
        public string cmemo { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public System.DateTime dindate { get; set; }
        public string cinpersoncode { get; set; }
        public Nullable<decimal> iasnline { get; set; }
        public Nullable<decimal> cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string stockcurrentdetailid { get; set; }
        public string inbillcticketcode { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string asn_d_ids { get; set; }
        public Nullable<decimal> scantype { get; set; }
        public string SN_CODE20 { get; set; }
        public string site { get; set; }
        public string wire { get; set; }
    }
}
