//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_QueryInOutSummaryReport
    {
        public string ID { get; set; }
        public string cinvcode { get; set; }
        public string cspecifications { get; set; }
        public Nullable<decimal> beginstocksummary { get; set; }
        public Nullable<decimal> insummary { get; set; }
        public Nullable<decimal> outsummary { get; set; }
        public Nullable<decimal> endstocksunmary { get; set; }
    }
}
