//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_INASSIT_BASE_CARGOSPACE
    {
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string caccountid { get; set; }
        public string coperatorname { get; set; }
        public string guid { get; set; }
        public string casnid { get; set; }
    }
}
