//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_DIGITALSINGE
    {
        public string resp_dept { get; set; }
        public string erpcode { get; set; }
        public Nullable<decimal> start_quantity { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<decimal> partcount { get; set; }
        public Nullable<decimal> oassitallno { get; set; }
        public Nullable<decimal> oassitpartno { get; set; }
        public Nullable<decimal> oassitallyes { get; set; }
        public Nullable<decimal> tempbillallno { get; set; }
        public Nullable<decimal> tempbillpartno { get; set; }
        public Nullable<decimal> tempbillallyes { get; set; }
        public Nullable<decimal> obillallno { get; set; }
        public Nullable<decimal> obillpartno { get; set; }
        public Nullable<decimal> obillallyes { get; set; }
        public Nullable<decimal> qallyes { get; set; }
        public string statename { get; set; }
        public string qallcinvcode { get; set; }
        public string ID { get; set; }
    }
}
