//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_BASE_PART_CARGOSPACE
    {
        public string cpartid { get; set; }
        public string cpositioncode { get; set; }
        public string ccreateownercode { get; set; }
        public string guid { get; set; }
        public int id { get; set; }
    }
}
