//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_INBILLTOTALQTY
    {
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> totalqty { get; set; }
        public string casnid { get; set; }
        public string userno { get; set; }
    }
}
