//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_QueryInOutdetailsReport
    {
        public string ID { get; set; }
        public string createDate { get; set; }
        public string cticketcode { get; set; }
        public string cinvcode { get; set; }
        public string typename { get; set; }
        public string ERPCODE { get; set; }
        public Nullable<decimal> insummary { get; set; }
        public Nullable<decimal> outsummary { get; set; }
        public Nullable<decimal> stocksummary { get; set; }
        public string ymonth { get; set; }
    }
}
