//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_BASE_DEPARTMENT
    {
        public string id { get; set; }
        public Nullable<int> error_flag { get; set; }
        public string DEPARTMENTNO { get; set; }
        public string DEPARTMENTNAME { get; set; }
    }
}
