//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_SELECTASND
    {
        public string asn_ids { get; set; }
        public string asn_id { get; set; }
        public string userno { get; set; }
        public string guid { get; set; }
        public System.DateTime createdate { get; set; }
        public string ID { get; set; }
    }
}
