//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_STOCK_SNRESET
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cpositioncode { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> sn_qty { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string createuser { get; set; }
    }
}
