//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_STOCK_CURRENT_SN
    {
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string sncode { get; set; }
        public string datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string weeks { get; set; }
    }
}
