//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_INANDOUTBILL
    {
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string worktype { get; set; }
        public string cticketcode { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string createuser { get; set; }
        public string cerpcode { get; set; }
        public string typename { get; set; }
        public string typecode { get; set; }
        public string ID { get; set; }
        public string PalletCode { get; set; }
        public string OldCinvCode { get; set; }
        public Nullable<decimal> CurrentStockQTY { get; set; }
        public string WorkTypeName { get; set; }
    }
}
