//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSINTEFACEFORASNCHANGE
    {
        public string id { get; set; }
        public string erpcode { get; set; }
        public string entity_id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cinverpcode { get; set; }
        public Nullable<decimal> oldnum { get; set; }
        public Nullable<decimal> nownum { get; set; }
        public string type { get; set; }
        public Nullable<decimal> transtype { get; set; }
        public string cstatus { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string last_upd_owner { get; set; }
        public Nullable<System.DateTime> last_upd_time { get; set; }
        public string cmemo { get; set; }
    }
}
