//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_TIME_CONFIG
    {
        public string id { get; set; }
        public decimal tran_type { get; set; }
        public string tran_erpcode { get; set; }
        public System.DateTime tran_time { get; set; }
        public System.DateTime disable_time { get; set; }
        public string cticketcode { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string typename { get; set; }
    }
}
