//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFunction
    {
        public string ID { get; set; }
        public string userno { get; set; }
        public string username { get; set; }
        public string funcno { get; set; }
        public string funcname { get; set; }
        public string extend1 { get; set; }
        public string modno { get; set; }
    }
}
