//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ALLOCATE_AUTO
    {
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditperson { get; set; }
        public Nullable<System.DateTime> daudittime { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string cerpcode { get; set; }
        public string id { get; set; }
        public string cdefine2 { get; set; }
        public string deliveryuser { get; set; }
        public Nullable<System.DateTime> deliverytime { get; set; }
        public string typename { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> debittime { get; set; }
        public string debitowner { get; set; }
        public string adcinvcode { get; set; }
        public System.DateTime dindate { get; set; }
    }
}
