//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ALLOCATE_DReport
    {
        public Nullable<long> rum { get; set; }
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public decimal iquantity { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string ctopositioncode { get; set; }
        public string ctoposition { get; set; }
        public string cinpersoncode { get; set; }
        public System.DateTime dindate { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditperson { get; set; }
        public Nullable<System.DateTime> daudittime { get; set; }
        public string cstatus { get; set; }
        public string ALLOTYPE { get; set; }
        public string workTypeName { get; set; }
        public string cspecifications { get; set; }
    }
}
