//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AsrsList_New
    {
        public int WmsTskId { get; set; }
        public string CmdSno { get; set; }
        public string CmdSts { get; set; }
        public string PRT { get; set; }
        public string StnNo { get; set; }
        public string CmdMode { get; set; }
        public string Loc { get; set; }
        public string NewLoc { get; set; }
        public string LocSize { get; set; }
        public string RodID { get; set; }
        public string Trace { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string Result { get; set; }
        public string TrnNo { get; set; }
        public Nullable<int> BillingStatus { get; set; }
        public string CreateUser { get; set; }
        public string CmdNO { get; set; }
        public string LineId { get; set; }
        public string PLCD51 { get; set; }
        public string cmdstsName { get; set; }
        public string cmdmodeName { get; set; }
        public string ids { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cticketcode { get; set; }
        public string caseTypeName { get; set; }
        public string caseType { get; set; }
        public string LOC_CODE { get; set; }
        public string LOC_NAME { get; set; }
        public string NEWLOC_CODE { get; set; }
        public string NEWLOC_NAME { get; set; }
    }
}
