//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_PART_BOM
    {
        public string ID { get; set; }
        public string CPARTNUMBER { get; set; }
        public string CPARTNAME { get; set; }
        public string CTYPE { get; set; }
    }
}
