//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_AREA
    {
        public string id { get; set; }
        public string area_name { get; set; }
        public string handover_cargo { get; set; }
        public string handover_cargo_name { get; set; }
        public string flag { get; set; }
        public string memo { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string is_control_New { get; set; }
        public string is_control { get; set; }
    }
}
