//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_VENDOR
    {
        public string ids { get; set; }
        public string cvendorid { get; set; }
        public string cvendor { get; set; }
        public string ccontactperson { get; set; }
        public string cphone { get; set; }
        public string caddress { get; set; }
        public string ctnpe { get; set; }
        public Nullable<decimal> ilevel { get; set; }
        public string calias { get; set; }
        public string cerpcode { get; set; }
        public string cmemo { get; set; }
        public string cstatus { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
