//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_base_bar_sn
    {
        public string id { get; set; }
        public string sn_code { get; set; }
        public string cinvcode { get; set; }
        public string cinvcode_name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string cstatus { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string SN_TYPE { get; set; }
        public string BAR_TYPE { get; set; }
        public string Vendor { get; set; }
        public string DateCode { get; set; }
    }
}
