//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bar_pallet_m
    {
        public string id { get; set; }
        public string palletno { get; set; }
        public string carton_no { get; set; }
        public string cinvbarcode { get; set; }
        public Nullable<decimal> qty { get; set; }
    }
}
