//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_CARGOSPACE_PK
    {
        public string ID { get; set; }
        public string IDS { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public decimal iqty { get; set; }
        public string wtype { get; set; }
        public string ctype { get; set; }
        public string ISUSED { get; set; }
    }
}
