//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_OPERATOR
    {
        public string id { get; set; }
        public string caccountid { get; set; }
        public string coperatorname { get; set; }
        public string calias { get; set; }
        public string cerpcode { get; set; }
        public string cduty { get; set; }
        public string cdepartment { get; set; }
        public string cphone { get; set; }
        public string cshift { get; set; }
        public string cstatus { get; set; }
        public string ccreateowner { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string cstatus_New { get; set; }
    }
}
