//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_CLIENT
    {
        public string id { get; set; }
        public string cclientid { get; set; }
        public string cclientname { get; set; }
        public string cstatus { get; set; }
        public string ccontactperson { get; set; }
        public string cphone { get; set; }
        public string caddress { get; set; }
        public string ctype { get; set; }
        public string calias { get; set; }
        public Nullable<decimal> ilever { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cmemo { get; set; }
        public string cerpcode { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string cstatusname { get; set; }
    }
}
