//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_base_cargospace_temp
    {
        public string 储位编码 { get; set; }
        public string 储位名称 { get; set; }
        public string 最大量 { get; set; }
        public string 备注 { get; set; }
        public string 区域 { get; set; }
        public string 状态 { get; set; }
        public string 种类 { get; set; }
        public string 所属仓库ID { get; set; }
        public string 优先级 { get; set; }
        public string 长 { get; set; }
        public string 宽 { get; set; }
        public string 高 { get; set; }
        public string 体积 { get; set; }
        public string 用途 { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public string 终止日期 { get; set; }
        public string 助记码 { get; set; }
        public string ERP编码 { get; set; }
        public string 是否允许混放 { get; set; }
        public string 是否允许调拨 { get; set; }
        public string 重量 { get; set; }
        public string 重量单位 { get; set; }
        public string 材积 { get; set; }
        public string 材积单位 { get; set; }
        public string 线别 { get; set; }
        public string 是否存在栈板 { get; set; }
    }
}
