//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_base_warehouse_temp
    {
        public string id { get; set; }
        public string 仓库编码 { get; set; }
        public string 仓库名称 { get; set; }
        public string 仓库类型 { get; set; }
        public string 供应商编码 { get; set; }
        public string 供应商名称 { get; set; }
        public string 电话 { get; set; }
        public string 状态 { get; set; }
        public string 是否保税仓 { get; set; }
        public string 是否良品仓 { get; set; }
        public string 企业编号 { get; set; }
        public string 据点编号 { get; set; }
        public string 应用组织 { get; set; }
        public string 备注 { get; set; }
    }
}
