//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_base_part_temp
    {
        public string id { get; set; }
        public string 料号 { get; set; }
        public string 品名 { get; set; }
        public string 类型 { get; set; }
        public string 类别 { get; set; }
        public string ERP编码 { get; set; }
        public string 毛重 { get; set; }
        public string 净重 { get; set; }
        public string 重量单位 { get; set; }
        public string 单位 { get; set; }
        public string 参考单位 { get; set; }
        public string 长 { get; set; }
        public string 宽 { get; set; }
        public string 高 { get; set; }
        public string 材积 { get; set; }
        public string 材积单位 { get; set; }
        public string 终止日期 { get; set; }
        public string 状态 { get; set; }
        public string 是否保税 { get; set; }
        public string 是否免检 { get; set; }
        public string 是否预警 { get; set; }
        public string 默认仓库 { get; set; }
        public string 默认储位 { get; set; }
        public string 默认供应商 { get; set; }
        public string 上架规则 { get; set; }
        public string 下架规则 { get; set; }
        public string 条码规则 { get; set; }
        public string 版本 { get; set; }
        public string 企业编号 { get; set; }
        public string 据点编号 { get; set; }
        public string 应用组织 { get; set; }
        public string 用途 { get; set; }
        public string 备注 { get; set; }
        public string 助记码 { get; set; }
        public string 规格 { get; set; }
    }
}
