//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_CARGOSPACEListQuery
    {
        public string id { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<decimal> imaxcapacity { get; set; }
        public string cmemo { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public string cstatus { get; set; }
        public string ctype { get; set; }
        public string warehouseid { get; set; }
        public Nullable<decimal> ipriority { get; set; }
        public Nullable<decimal> ilength { get; set; }
        public Nullable<decimal> iwidth { get; set; }
        public Nullable<decimal> iheight { get; set; }
        public Nullable<decimal> ivolume { get; set; }
        public string cusetype { get; set; }
        public string cx { get; set; }
        public string cy { get; set; }
        public string cz { get; set; }
        public Nullable<System.DateTime> dexpiredate { get; set; }
        public string calias { get; set; }
        public string cerpcode { get; set; }
        public Nullable<decimal> ipermitmix { get; set; }
        public string lineid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<decimal> ioccupyqty { get; set; }
        public Nullable<decimal> is_allo { get; set; }
        public string lastcstatus { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastupdatetime { get; set; }
        public string lastupdateowner { get; set; }
        public string pallet_code { get; set; }
        public string productcode { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> volumeunit { get; set; }
        public Nullable<decimal> occupyweight { get; set; }
        public Nullable<decimal> occupyvolume { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> weightunit { get; set; }
        public string cwareid { get; set; }
        public string wID { get; set; }
        public string wName { get; set; }
    }
}
