//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CARGOSPACE_Report
    {
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cstatus { get; set; }
        public Nullable<decimal> imaxcapacity { get; set; }
        public string calias { get; set; }
        public string ctype { get; set; }
        public Nullable<decimal> ipermitmix { get; set; }
        public string id { get; set; }
        public string statusname { get; set; }
        public string ipermitmixname { get; set; }
    }
}
