//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CHAYIReport_Report
    {
        public string CTICKETCODE { get; set; }
        public string CCHECKNAME { get; set; }
        public string Cerpcode { get; set; }
        public string CHECKTYPE { get; set; }
        public string CHECKCode { get; set; }
        public string CWAREID { get; set; }
        public string CWARENAME { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CPOSITION { get; set; }
        public string CINVCODE { get; set; }
        public Nullable<decimal> IQT { get; set; }
        public string Cdefine2 { get; set; }
        public Nullable<decimal> IQTNow0 { get; set; }
        public Nullable<decimal> IQTNow1 { get; set; }
        public Nullable<System.DateTime> ActualTime0 { get; set; }
        public Nullable<System.DateTime> ActualTime1 { get; set; }
        public Nullable<decimal> diffCount0 { get; set; }
        public Nullable<decimal> diffCount1 { get; set; }
        public string ccheckpersoncode { get; set; }
        public System.DateTime DCHECKDATE { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
    }
}
