//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CHAYIReport
    {
        public string cticketcode { get; set; }
        public string ccheckname { get; set; }
        public string CHECKCode { get; set; }
        public string cerpcode { get; set; }
        public string checktype { get; set; }
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> iqt { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<decimal> iqtnow0 { get; set; }
        public Nullable<decimal> iqtnow1 { get; set; }
        public Nullable<System.DateTime> actualtime0 { get; set; }
        public Nullable<System.DateTime> actualtime1 { get; set; }
        public Nullable<decimal> diffcount0 { get; set; }
        public Nullable<decimal> diffcount1 { get; set; }
        public string ccheckpersoncode { get; set; }
        public string dcheckdate { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
        public string cspecifications { get; set; }
    }
}
