//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMD_MST_RGV
    {
        public string CmdSno { get; set; }
        public int WmsTskId { get; set; }
        public string Cmdsts { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string PRT { get; set; }
        public string CmdMode { get; set; }
        public string StnNo { get; set; }
        public string Loc { get; set; }
        public string NewLoc { get; set; }
        public string LocSize { get; set; }
        public string RodID { get; set; }
        public string Trace { get; set; }
        public string Result { get; set; }
        public string TrnNo { get; set; }
        public Nullable<int> BillingStatus { get; set; }
        public string CreateUser { get; set; }
        public string BillingNO { get; set; }
        public string CmdNO { get; set; }
        public string LineId { get; set; }
        public string PLCD51 { get; set; }
        public string CTICKETCODE { get; set; }
        public string PACKAGENO { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> updata { get; set; }
        public string msg { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public string Height { get; set; }
        public string Reason { get; set; }
        public string PC { get; set; }
        public string AreaId { get; set; }
        public string CraneStataus { get; set; }
    }
}
