//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMD_AgvTask
    {
        public string id { get; set; }
        public string reqtime { get; set; }
        public string reqcode { get; set; }
        public string clientcode { get; set; }
        public string tokencode { get; set; }
        public string interfacename { get; set; }
        public string tasktyp { get; set; }
        public string wbcode { get; set; }
        public string podcode { get; set; }
        public string poddir { get; set; }
        public string podtyp { get; set; }
        public string materiallot { get; set; }
        public string priority { get; set; }
        public string taskcode { get; set; }
        public string agvcode { get; set; }
        public string data { get; set; }
        public string vendorname { get; set; }
        public string status { get; set; }
        public string CreateOwner { get; set; }
        public string Createtime { get; set; }
        public string value { get; set; }
    }
}
