//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMD_MST
    {
        public string PACKAGENO { get; set; }
        public string REMARK { get; set; }
        public string CmdSts { get; set; }
        public string LineId { get; set; }
        public string StnNo { get; set; }
        public string LOC { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string CTICKETCODE { get; set; }
        public string Result { get; set; }
        public int WmsTskId { get; set; }
        public string PRT { get; set; }
        public string NewLoc { get; set; }
        public string CmdMode { get; set; }
        public string CmdSno { get; set; }
        public string TaskNO { get; set; }
    }
}
