//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_digitalsignage
    {
        public Nullable<long> RowNum { get; set; }
        public string id { get; set; }
        public string RESP_DEPT { get; set; }
        public string ERPCODE { get; set; }
        public Nullable<decimal> START_QUANTITY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<decimal> PARTCOUNT { get; set; }
        public Nullable<decimal> OASSITALLNO { get; set; }
        public Nullable<decimal> OASSITPARTNO { get; set; }
        public Nullable<decimal> OASSITALLYES { get; set; }
        public Nullable<decimal> TEMPBILLALLNO { get; set; }
        public Nullable<decimal> TEMPBILLPARTNO { get; set; }
        public Nullable<decimal> TEMPBILLALLYES { get; set; }
        public Nullable<decimal> OBILLALLNO { get; set; }
        public Nullable<decimal> OBILLPARTNO { get; set; }
        public Nullable<decimal> OBILLALLYES { get; set; }
        public Nullable<decimal> QALLYES { get; set; }
        public string STATENAME { get; set; }
        public string QALLCINVCODE { get; set; }
        public Nullable<System.DateTime> start_date_mo { get; set; }
    }
}
