//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DiffTime_Report
    {
        public string ID { get; set; }
        public string cwarehousecode { get; set; }
        public string cwarehouse { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string calias { get; set; }
        public string cspecifications { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> LastInDate { get; set; }
        public Nullable<System.DateTime> LastOutDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> DayDiff { get; set; }
    }
}
