//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EBS_TRAN_TEST
    {
        public decimal transaction_id { get; set; }
        public string item { get; set; }
        public string subinventory_code { get; set; }
        public string locator { get; set; }
        public string transaction_source_name { get; set; }
        public string transaction_type_name { get; set; }
        public string transaction_action_name { get; set; }
        public Nullable<decimal> transaction_source_id { get; set; }
        public string transaction_reference { get; set; }
        public string source_code { get; set; }
        public string wms_user { get; set; }
        public string wms_num { get; set; }
        public Nullable<decimal> trx_source_line_id { get; set; }
        public Nullable<decimal> ds_num { get; set; }
        public string receipt_num { get; set; }
        public string transfer_subinventory { get; set; }
        public string transfer_locator { get; set; }
        public string source_name { get; set; }
        public decimal transaction_quantity { get; set; }
        public System.DateTime transaction_date { get; set; }
    }
}
