//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetInAsn_Ten
    {
        public Nullable<long> RowNum { get; set; }
        public string ID { get; set; }
        public string CCREATEOWNERCODE { get; set; }
        public System.DateTime DCREATETIME { get; set; }
        public string CAUDITPERSONCODE { get; set; }
        public Nullable<System.DateTime> DAUDITDATE { get; set; }
        public string CTICKETCODE { get; set; }
        public string CSTATUS { get; set; }
        public string CPO { get; set; }
        public string ITYPE { get; set; }
        public string CERPCODE { get; set; }
        public string WORKTYPE { get; set; }
        public string worktypeName { get; set; }
    }
}
