//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ImportDateList
    {
        public string ID { get; set; }
        public string WO { get; set; }
        public string WO_QTY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string SHIFT { get; set; }
        public string SPECIAL { get; set; }
        public string LINEBODY { get; set; }
        public string Models { get; set; }
        public string CREATE_OWNER { get; set; }
        public Nullable<System.DateTime> LAST_UPD_TIME { get; set; }
        public string LAST_UPD_OWNER { get; set; }
        public string DEPARTMENTNO { get; set; }
        public string ISCOUNTJOBTIME { get; set; }
        public Nullable<System.DateTime> ONLINETIME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string SEC_CINVCODE { get; set; }
    }
}
