//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INBILL
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string cauditperson { get; set; }
        public Nullable<System.DateTime> daudittime { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string status_name { get; set; }
        public string casnid { get; set; }
        public string asncode { get; set; }
        public System.DateTime dindate { get; set; }
        public string cmemo { get; set; }
        public string cerpcode { get; set; }
        public string typename { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> debittime { get; set; }
        public string debitowner { get; set; }
        public decimal itype { get; set; }
        public string palletcode { get; set; }
        public string WORKTYPE { get; set; }
        public string worktypeName { get; set; }
        public Nullable<int> operationtype { get; set; }
    }
}
