//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INASNSplit
    {
        public string IDS { get; set; }
        public string ID { get; set; }
        public string CSTATUS { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public Nullable<decimal> IQUANTITY { get; set; }
        public string CINVBARCODE { get; set; }
        public string CBATCH { get; set; }
        public string CERPCODELINE { get; set; }
        public string PO_NUMBERNAME { get; set; }
        public string PO_LINENUMBERNAME { get; set; }
        public string MSTATUS { get; set; }
        public Nullable<decimal> InBill_Qty { get; set; }
        public Nullable<decimal> InBilled_Qty { get; set; }
        public Nullable<decimal> LessQty { get; set; }
    }
}
