//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INOutType
    {
        public string TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public string CERPCODE { get; set; }
        public string TRANSACTION_ACTION_ID { get; set; }
        public string TRANSACTION_SOURCE_TYPE_ID { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string TYPE_CLASS { get; set; }
        public string IS_ZF { get; set; }
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
        public string ENABLE { get; set; }
        public string ENABLEUSER { get; set; }
        public Nullable<System.DateTime> ENABLEDATE { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string T { get; set; }
        public string IsMatchSo { get; set; }
        public string IsMatchVendor { get; set; }
    }
}
