//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_InAsn_PO
    {
        public string cerpcode { get; set; }
        public string LINE_NUM { get; set; }
        public Nullable<decimal> RECEIPT_LINE_NUM { get; set; }
        public string cpartnumber { get; set; }
        public string cpartname { get; set; }
        public string SEGMENT1 { get; set; }
        public Nullable<decimal> qty { get; set; }
    }
}
