//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INBILL_REPORT
    {
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public string cwareid { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string typename { get; set; }
        public string ccreateownercode { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public decimal itype { get; set; }
        public string worktype { get; set; }
        public string TypeCode { get; set; }
        public string cspecifications { get; set; }
    }
}
