//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_InAsnEmt
    {
        public string ids { get; set; }
        public string cinvbarcode { get; set; }
        public string PalletCode { get; set; }
        public string id { get; set; }
        public string cerpcode { get; set; }
        public string itype { get; set; }
        public string cerpcodeline { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cstatus { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public string cticketcode { get; set; }
        public string WORKTYPE { get; set; }
        public string worktypeName { get; set; }
    }
}
