//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INASN
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditpersoncode { get; set; }
        public Nullable<System.DateTime> dauditdate { get; set; }
        public string cticketcode { get; set; }
        public string cstatus { get; set; }
        public string statusname { get; set; }
        public string cpo { get; set; }
        public string itype { get; set; }
        public string typename { get; set; }
        public string cerpcode { get; set; }
        public string ddefine3 { get; set; }
        public string ddefine4 { get; set; }
        public string isspecialwipreturn { get; set; }
        public string reasoncode { get; set; }
        public string reasoncontent { get; set; }
        public string WORKTYPE { get; set; }
        public string worktypeName { get; set; }
        public string inasn_ia_id { get; set; }
        public int oby { get; set; }
    }
}
