//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INBILL_DAndSN
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cstatus { get; set; }
        public string cstatus_name { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cerpcodeline { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<System.DateTime> dindate { get; set; }
        public string inbilltype { get; set; }
        public Nullable<int> lineid { get; set; }
        public string sn_code { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string PalletCode { get; set; }
    }
}
