//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Inasn_D_Edit
    {
        public Nullable<int> lineId { get; set; }
        public string ids { get; set; }
        public string id { get; set; }
        public string cstatus { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cinvbarcode { get; set; }
        public string cbatch { get; set; }
        public string cerpcodeline { get; set; }
        public string po_numbername { get; set; }
        public string po_linenumbername { get; set; }
        public string cpo { get; set; }
        public Nullable<decimal> ipoline { get; set; }
        public string mstatus { get; set; }
        public Nullable<decimal> inbill_qty { get; set; }
        public Nullable<decimal> inbilled_qty { get; set; }
        public string calias { get; set; }
        public string productcode { get; set; }
        public string cspecifications { get; set; }
    }
}
