//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IN_MERGE_PALLETE
    {
        public string palletcode { get; set; }
        public string sn_code { get; set; }
        public string cstatus { get; set; }
        public string cerpcode { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string cticketcode { get; set; }
        public string INASNID { get; set; }
        public string INASNCODE { get; set; }
        public string ID { get; set; }
        public string OUTASNCODE_PALLET { get; set; }
        public string OUTBILLCODE_PALLET { get; set; }
        public string INASNCODE_PALLET { get; set; }
        public string INBILLCODE_PALLET { get; set; }
        public string CREATEUSER { get; set; }
    }
}
