//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INASSIT_Report
    {
        public string id { get; set; }
        public string inasncticketcode { get; set; }
        public string inassicticketcode { get; set; }
        public string cerpcode { get; set; }
        public string cwareid { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cinvbarcode { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string typename { get; set; }
        public string cinpersoncode { get; set; }
        public Nullable<System.DateTime> dindate { get; set; }
        public string intype { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
    }
}
