//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INASN_REPORT
    {
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string typename { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public decimal inassit_qty { get; set; }
        public decimal inbill_qty { get; set; }
        public decimal inbilled_qty { get; set; }
        public int iswebcreatebill { get; set; }
        public string iswebcreatebillname { get; set; }
        public string cpo { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string itype { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
        public string cspecifications { get; set; }
    }
}
