//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INBILL_DSN
    {
        public string id { get; set; }
        public string inbill_id { get; set; }
        public string inbill_d_ids { get; set; }
        public string sn_code { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string DisplayTYPE { get; set; }
        public string worktype { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string furnaceno { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> lastvpdtime { get; set; }
        public string lastvpdowner { get; set; }
        public Nullable<System.DateTime> transedtime { get; set; }
        public string SN_CODE20 { get; set; }
        public string PalletCode { get; set; }
        public string RULECODE { get; set; }
    }
}
