//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JIANHUO_REPORT
    {
        public string id { get; set; }
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvbarcode { get; set; }
        public string cinvcode { get; set; }
        public decimal iquantity { get; set; }
        public string typename { get; set; }
        public string coutpersoncode { get; set; }
        public System.DateTime doutdate { get; set; }
        public string outassitcticketcode { get; set; }
        public string cerpcode { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public decimal itype { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
        public string cerpcode1 { get; set; }
        public string cspecifications { get; set; }
    }
}
