//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderFinish_Stock
    {
        public Nullable<System.Guid> Id { get; set; }
        public string OrderNo { get; set; }
        public string CustomOrderNo { get; set; }
        public string CustomId { get; set; }
        public string CustomName { get; set; }
        public int OrderLine { get; set; }
        public string CinvCode { get; set; }
        public string CinvName { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cwarehousecode { get; set; }
        public string cwarehouse { get; set; }
        public Nullable<decimal> AllQty { get; set; }
        public Nullable<decimal> LockQty { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
