//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORA_TEST
    {
        public string itype2 { get; set; }
        public string itype { get; set; }
        public string ERPCODE { get; set; }
        public string CTICKETCODE { get; set; }
        public string CPO { get; set; }
        public System.DateTime DCREATETIME { get; set; }
    }
}
