//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTASN_SPLIT
    {
        public string OUTASNID { get; set; }
        public string CSO { get; set; }
        public Nullable<decimal> ISOLINE { get; set; }
        public string CINVNAME { get; set; }
        public string CINVCODE { get; set; }
        public string CINVBARCODE { get; set; }
        public decimal IQUANTITY { get; set; }
        public string CSTATUS { get; set; }
        public string CBATCH { get; set; }
        public string CERPCODELINE { get; set; }
        public string IDS { get; set; }
        public Nullable<decimal> OutBill_Qty { get; set; }
        public Nullable<decimal> OutBilled_Qty { get; set; }
        public Nullable<decimal> LessQty { get; set; }
    }
}
