//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTMIXED_JF_List
    {
        public Nullable<long> ROWNUM { get; set; }
        public string ERPCODE { get; set; }
        public decimal OTYPE { get; set; }
        public string OTYPENAME { get; set; }
        public decimal SUMQTY { get; set; }
        public decimal YMIXEDQTY { get; set; }
        public Nullable<decimal> WMIXEDQTY { get; set; }
        public decimal KMIXEDQTY { get; set; }
        public decimal KJFQTY { get; set; }
    }
}
