//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTBILL
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditperson { get; set; }
        public Nullable<System.DateTime> daudittime { get; set; }
        public string cclientcode { get; set; }
        public string cclient { get; set; }
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public string coutasnid { get; set; }
        public string cmemo { get; set; }
        public System.DateTime dindate { get; set; }
        public string cso { get; set; }
        public string bccode { get; set; }
        public decimal otype { get; set; }
        public string typename { get; set; }
        public string cstatus { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> debittime { get; set; }
        public string debitowner { get; set; }
        public string sn_code { get; set; }
        public Nullable<int> operationtype { get; set; }
        public string worktype { get; set; }
        public string cstatus_name { get; set; }
    }
}
