//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTASN_DL
    {
        public string id { get; set; }
        public string cso { get; set; }
        public Nullable<decimal> isoline { get; set; }
        public string cinvname { get; set; }
        public string cinvcode { get; set; }
        public string cinvbarcode { get; set; }
        public decimal iquantity { get; set; }
        public string cstatus { get; set; }
        public string cbatch { get; set; }
        public string cerpcodeline { get; set; }
        public string ids { get; set; }
        public string MSTATUS { get; set; }
        public Nullable<decimal> OutBill_Qty { get; set; }
        public Nullable<decimal> OutBilled_Qty { get; set; }
        public Nullable<int> lineid { get; set; }
        public string cspecifications { get; set; }
    }
}
