//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTMIXED_D
    {
        public string CREATERUSERName { get; set; }
        public string ID { get; set; }
        public string IDS { get; set; }
        public string OUTCTICKETCODE { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public decimal QTY { get; set; }
        public string CINVBARCODE { get; set; }
        public string CSTATUS { get; set; }
        public string CREATERUSER { get; set; }
        public Nullable<System.DateTime> CREATERTIME { get; set; }
        public string REMARK { get; set; }
        public string CDEFIEND1 { get; set; }
        public string CDEFIEND2 { get; set; }
        public string CDEFIEND3 { get; set; }
    }
}
