//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTASNList
    {
        public string id { get; set; }
        public string ccreateownercode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string cauditpersoncode { get; set; }
        public Nullable<System.DateTime> dauditdate { get; set; }
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public string cstatus { get; set; }
        public string flag_name { get; set; }
        public decimal itype { get; set; }
        public string typename { get; set; }
        public string cdefine2 { get; set; }
        public decimal is_merge { get; set; }
        public Nullable<System.DateTime> START_DATES { get; set; }
        public string SHIFTS { get; set; }
        public string is_mergename { get; set; }
        public Nullable<int> IsSpecialWipIssue { get; set; }
        public string special_out { get; set; }
        public string smttype { get; set; }
        public Nullable<int> is_cj { get; set; }
        public string cstatusname { get; set; }
        public string smttypeint { get; set; }
        public string cso { get; set; }
        public string worktype { get; set; }
    }
}
