//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OutAsn_Adj
    {
        public string CCREATEOWNERCODE { get; set; }
        public System.DateTime DCREATETIME { get; set; }
        public string CAUDITPERSONCODE { get; set; }
        public Nullable<System.DateTime> DAUDITDATE { get; set; }
        public string CTICKETCODE { get; set; }
        public string CSTATUS { get; set; }
        public string CERPCODE { get; set; }
        public string CSO { get; set; }
        public string ID { get; set; }
    }
}
