//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OUTBILL_SN
    {
        public string id { get; set; }
        public string outbill_id { get; set; }
        public string outbill_d_ids { get; set; }
        public string sn_code { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string cinvcode { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string worktype { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<System.DateTime> lastvpdtime { get; set; }
        public string lastvpdowner { get; set; }
        public string scan_ids { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string furnaceno { get; set; }
        public string outbilltype { get; set; }
        public string palletcode { get; set; }
        public string cso { get; set; }
        public string vendorcode { get; set; }
        public string RULECODE { get; set; }
        public Nullable<decimal> ALLQTY { get; set; }
    }
}
