//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PartList_ByWareHouse
    {
        public string cwarehousecode { get; set; }
        public string cwarename { get; set; }
        public string area_code { get; set; }
        public string area_name { get; set; }
        public string cinvcode { get; set; }
        public string cpartname { get; set; }
        public string calias { get; set; }
        public string cspecifications { get; set; }
        public Nullable<decimal> sumqty { get; set; }
        public string cunits { get; set; }
    }
}
