//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PANDIANReport
    {
        public string id { get; set; }
        public string cticketcode { get; set; }
        public string ccheckname { get; set; }
        public string checktype { get; set; }
        public string checktypeName { get; set; }
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public decimal iquantity { get; set; }
        public string dcheckdate { get; set; }
        public Nullable<System.DateTime> dcreatetime { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
    }
}
