//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_QueryOutASND
    {
        public string cticketcode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> inum { get; set; }
        public Nullable<decimal> yjnum { get; set; }
        public Nullable<decimal> synum { get; set; }
        public string CMEMO { get; set; }
        public string cspecifications { get; set; }
        public Nullable<decimal> wzyNum { get; set; }
    }
}
