//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_InEmtList
    {
        public string STATUSNAME { get; set; }
        public string cstatus { get; set; }
        public string cerpcodeline { get; set; }
        public Nullable<int> LineID { get; set; }
        public string ids { get; set; }
        public string cinvcode { get; set; }
        public string cticketcode { get; set; }
        public decimal qty { get; set; }
        public string userno { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<decimal> Surplusqty { get; set; }
        public string WORKTYPE { get; set; }
        public string cerpcode { get; set; }
    }
}
