//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_OutMixed_DList
    {
        public string ID { get; set; }
        public string MIXEDCODE { get; set; }
        public string ERPCODE { get; set; }
        public Nullable<decimal> OTYPE { get; set; }
        public string OUTCTICKETCODE { get; set; }
        public string calias { get; set; }
        public string fg_cinvcode { get; set; }
        public Nullable<decimal> fg_qty { get; set; }
        public string flag_id { get; set; }
        public string flag_name { get; set; }
        public string IDS { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public string CINVBARCODE { get; set; }
        public decimal QTY { get; set; }
        public string REMARK { get; set; }
        public string CSTATUS { get; set; }
        public string MixStatusName { get; set; }
        public string AGVSite { get; set; }
        public string wo { get; set; }
        public Nullable<System.DateTime> CREATERTIME { get; set; }
        public string outmixed_dCstatusName { get; set; }
        public string outmixed_dCstatus { get; set; }
        public Nullable<int> IQTY { get; set; }
    }
}
