//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_OutAssitList
    {
        public string id { get; set; }
        public string cticketcode { get; set; }
        public string cerpcode { get; set; }
        public System.DateTime dcreatetime { get; set; }
        public string typename { get; set; }
        public string shift { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string sec_cinvcode { get; set; }
        public string itype { get; set; }
        public Nullable<decimal> asnqty { get; set; }
        public Nullable<decimal> tempqty { get; set; }
    }
}
