//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_QueryTEMP_InBill_D
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cinvbarcode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public string CSPECIFICATIONS { get; set; }
        public System.DateTime dindate { get; set; }
    }
}
