//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_InAsnEmtList
    {
        public string ERPCODE { get; set; }
        public string CTICKETCODE { get; set; }
        public string OWNERCODE { get; set; }
        public System.DateTime DCREATETIME { get; set; }
        public string WORKTYPE { get; set; }
        public string worktypeName { get; set; }
        public string userno { get; set; }
        public string ID { get; set; }
        public string itype { get; set; }
        public string typename { get; set; }
    }
}
