//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_QueryINASSIT
    {
        public string CTICKETCODE { get; set; }
        public string casnid { get; set; }
        public string cpo { get; set; }
        public string CERPCODE { get; set; }
        public Nullable<System.DateTime> DCREATETIME { get; set; }
        public string OCRITICAL_PART { get; set; }
        public Nullable<decimal> CRITICAL_PART { get; set; }
        public string typename { get; set; }
        public string typecode { get; set; }
        public string cvender { get; set; }
        public string CINVCODE { get; set; }
        public string cinvname { get; set; }
        public string cspecifications { get; set; }
        public string ids { get; set; }
        public string caccountid { get; set; }
        public string userno { get; set; }
    }
}
