//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_INEmtQueryList
    {
        public string SN_CODE { get; set; }
        public string PALLEDCODE { get; set; }
        public string STATUSNAME { get; set; }
        public string cstatus { get; set; }
        public string ERPCODE { get; set; }
        public string CINVCODE { get; set; }
        public decimal QTY { get; set; }
        public Nullable<System.DateTime> EMTTIME { get; set; }
        public string EMTUSERNO { get; set; }
        public string CTICKETCODE { get; set; }
        public string ID { get; set; }
        public string WORKTYPE { get; set; }
        public string WORKTYPENAME { get; set; }
    }
}
