//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_Allocate_D
    {
        public string CINVCODE { get; set; }
        public decimal IQUANTITY { get; set; }
        public string CTICKETCODE { get; set; }
        public decimal YJnum { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CTOPOSITIONCODE { get; set; }
        public string CINVNAME { get; set; }
        public string ID { get; set; }
        public string IDS { get; set; }
        public string CRITICAL_PART { get; set; }
        public Nullable<decimal> SYnum { get; set; }
    }
}
