//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_AllocateList
    {
        public string CTICKETCODE { get; set; }
        public string CERPCODE { get; set; }
        public string COPERATORNAME { get; set; }
        public string CCREATEOWNERCODE { get; set; }
        public string DCREATETIME { get; set; }
        public string FLAG_NAME { get; set; }
        public string ALLOTYPE { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public string CRITICAL_PART { get; set; }
        public string CINVCODE { get; set; }
    }
}
