//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_STOCK_ALLO_SCAN_D
    {
        public string CINVCODE { get; set; }
        public Nullable<decimal> IQUANTITY { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CTOPOSITIONCODE { get; set; }
        public string CSN { get; set; }
        public Nullable<decimal> CDATECODE { get; set; }
        public string ID { get; set; }
        public string cticketcode { get; set; }
    }
}
