//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_QueryOutASSIT
    {
        public string ids { get; set; }
        public string CTICKETCODE { get; set; }
        public string casnid { get; set; }
        public string cso { get; set; }
        public string cerpcode { get; set; }
        public System.DateTime DCREATETIME { get; set; }
        public string OCRITICAL_PART { get; set; }
        public Nullable<decimal> CRITICAL_PART { get; set; }
        public string typename { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string sec_cinvcode { get; set; }
        public decimal ITYPE { get; set; }
        public string CINVCODE { get; set; }
        public string SPECIAL { get; set; }
        public string SmtType { get; set; }
    }
}
