//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_OutBill_Items
    {
        public string cinvcode { get; set; }
        public string IDS { get; set; }
        public string ID { get; set; }
        public string status { get; set; }
        public Nullable<decimal> yfnum { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<decimal> yjfsl { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> ccjfsl { get; set; }
    }
}
