//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDA_InBillRevoke
    {
        public string SN_CODE { get; set; }
        public string itype { get; set; }
        public string PALLEDCODE { get; set; }
        public string ERPCODE { get; set; }
        public string CINVCODE { get; set; }
        public string CREATERTIME { get; set; }
        public string CTICKETCODE { get; set; }
        public string CSTATUS { get; set; }
        public string WORKTYPE { get; set; }
        public Nullable<decimal> CRITICAL_PART { get; set; }
        public string cerpcode { get; set; }
        public string worktypeName { get; set; }
        public string UserName { get; set; }
        public string ids { get; set; }
    }
}
