//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_QuickMIXED
    {
        public string id { get; set; }
        public string ids { get; set; }
        public string CERPCODE { get; set; }
        public string CTICKETCODE { get; set; }
        public string PALLETCODE { get; set; }
        public decimal QTY { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CPOSITION { get; set; }
        public string CINVBARCODE { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public decimal OTYPE { get; set; }
        public string OTYPENAME { get; set; }
    }
}
