//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rational_issue
    {
        public string cerpcodeline { get; set; }
        public string cinvcode { get; set; }
        public decimal iquantity { get; set; }
        public decimal inum { get; set; }
        public decimal tiquantity { get; set; }
        public decimal odiquantity { get; set; }
        public decimal oqty { get; set; }
        public Nullable<double> inum1 { get; set; }
    }
}
