//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ScanInAssitInfo
    {
        public string cPositionCode { get; set; }
        public string cPosition { get; set; }
        public string cInvCode { get; set; }
        public string cinvname { get; set; }
        public string cspecifications { get; set; }
        public decimal iNum { get; set; }
        public string cticketcode { get; set; }
        public Nullable<int> critical_part { get; set; }
        public string caccountid { get; set; }
        public decimal dounted { get; set; }
    }
}
