//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Seral_Details
    {
        public Nullable<System.Guid> id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string cticketcode { get; set; }
        public Nullable<int> SavedCount { get; set; }
        public string BillType { get; set; }
    }
}
