//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ShowSN_Stock
    {
        public Nullable<System.Guid> ID { get; set; }
        public string SN_CODE { get; set; }
        public string cinvcode { get; set; }
        public string cpositioncode { get; set; }
        public Nullable<decimal> sntype { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string ERPCODE { get; set; }
        public string VENDORCODE { get; set; }
    }
}
