//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ShowSNSplit
    {
        public string SN_CODE { get; set; }
        public string CINVCODE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> SNTYPE { get; set; }
        public string CPITIONCODE { get; set; }
    }
}
