//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Stock_CheckDiffSearch
    {
        public string cticketcode { get; set; }
        public string ccheckname { get; set; }
        public string cerpcode { get; set; }
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public decimal iquantity { get; set; }
        public Nullable<decimal> onenum { get; set; }
        public string onedate { get; set; }
        public string onename { get; set; }
        public Nullable<decimal> twonum { get; set; }
        public string twodate { get; set; }
        public string checktype { get; set; }
        public string twoname { get; set; }
        public Nullable<decimal> onediff { get; set; }
        public Nullable<decimal> twodiff { get; set; }
        public string dcheckdate { get; set; }
        public Nullable<int> ptype { get; set; }
    }
}
