//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_CHECKDBILL
    {
        public string cerpcode { get; set; }
        public string cticketcode { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string cstatus { get; set; }
        public string statusf { get; set; }
        public string flag_name { get; set; }
        public string checktype { get; set; }
        public string ccheckname { get; set; }
        public string cinvname { get; set; }
        public string ids { get; set; }
        public decimal qty { get; set; }
        public decimal iquantity { get; set; }
    }
}
