//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_CURRENT_List
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cwarename { get; set; }
        public string cwarehousecode { get; set; }
        public string cwarehouse { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cdatecode { get; set; }
        public decimal iqty { get; set; }
        public Nullable<decimal> ioccupyqty { get; set; }
        public Nullable<decimal> locknum { get; set; }
        public string cerpcode { get; set; }
        public string pallet_code { get; set; }
        public string calias { get; set; }
        public string palletcode { get; set; }
        public string cspecifications { get; set; }
    }
}
