//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_stock_current_adjust_d
    {
        public string id { get; set; }
        public string cstatus { get; set; }
        public string cwarehouse { get; set; }
        public string cwarehousecode { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> oriqty { get; set; }
        public string cunits { get; set; }
        public string cdatecode { get; set; }
        public string cbarcode { get; set; }
        public decimal ioccupyqty { get; set; }
        public string cmemo { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public Nullable<System.DateTime> ddefine3 { get; set; }
        public Nullable<System.DateTime> ddefine4 { get; set; }
        public Nullable<decimal> idefine5 { get; set; }
        public decimal iplanin { get; set; }
        public decimal iplanout { get; set; }
        public string palletcode { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> newqty { get; set; }
        public string cspecifications { get; set; }
    }
}
