//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_POSTITON
    {
        public string id { get; set; }
        public string wareid { get; set; }
        public string cwareid { get; set; }
        public string cwarename { get; set; }
        public string ctype { get; set; }
        public string ctyename { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<decimal> usage { get; set; }
        public string palletcode { get; set; }
        public string usagename { get; set; }
        public string hasPallet { get; set; }
        public string hasPalletname { get; set; }
    }
}
