//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Stock_DataCode_Edit
    {
        public string ids { get; set; }
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string lockqty { get; set; }
        public Nullable<decimal> ioccupyqty { get; set; }
    }
}
