//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_FORERP
    {
        public string 仓库 { get; set; }
        public string 料号 { get; set; }
        public string 品名 { get; set; }
        public string 助记码 { get; set; }
        public string 规格 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
    }
}
