//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_ElectBinCard
    {
        public string id { get; set; }
        public string cwarehouse { get; set; }
        public string cwarehousecode { get; set; }
        public string cposition { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string CDEFAULTVENDOR { get; set; }
        public string CSPECIFICATIONS { get; set; }
        public string sncode { get; set; }
        public string furnaceno { get; set; }
        public string PRODUCTCODE { get; set; }
        public string CDEFINE1 { get; set; }
        public string leader { get; set; }
        public string CWARENAME { get; set; }
        public Nullable<decimal> DATECODE { get; set; }
        public string STOCKTYPE { get; set; }
        public string cvendor { get; set; }
        public string inBillTypeName { get; set; }
    }
}
