//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_CURRENT
    {
        public string id { get; set; }
        public string cwarehousecode { get; set; }
        public string cwarehouse { get; set; }
        public string cdatecode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public decimal iqty { get; set; }
        public decimal ioccupyqty { get; set; }
        public decimal LockNum { get; set; }
    }
}
