//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_stock_checkedbill
    {
        public string checkbill_d_ids { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public string cpositioncode { get; set; }
        public string cinvcode { get; set; }
        public string cdefine2 { get; set; }
        public string ccheckpersoncode { get; set; }
        public System.DateTime DCHECKDATE { get; set; }
    }
}
