//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_Current_ALL
    {
        public string id { get; set; }
        public string cwarehouse { get; set; }
        public string cwarehousecode { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cdefine2 { get; set; }
        public string ctype { get; set; }
        public string palletcode { get; set; }
        public Nullable<decimal> iqty { get; set; }
        public string ERPCODE { get; set; }
    }
}
