//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK_BILLList
    {
        public string id { get; set; }
        public string checkbill_d_ids { get; set; }
        public decimal iquantity { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cwarename { get; set; }
        public string cwareid { get; set; }
        public System.DateTime dcheckdate { get; set; }
        public string ccheckname { get; set; }
        public string flag_name { get; set; }
        public string cstatus { get; set; }
    }
}
