//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_LOG
    {
        public string ID { get; set; }
        public string CaseNO { get; set; }
        public string ErrorNumber { get; set; }
        public string ERPCode { get; set; }
        public string ErrorMsg { get; set; }
        public string ModuleType { get; set; }
        public string ModuleTypeName { get; set; }
        public string SubModuleType { get; set; }
        public string SubModuleTypeName { get; set; }
        public string SourceType { get; set; }
        public string SourceTypeName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
