//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_PARAMETER
    {
        public string ID { get; set; }
        public string FLAG_ID { get; set; }
        public string FLAG_NAME { get; set; }
        public string FLAG_TYPE { get; set; }
        public Nullable<decimal> SORTID { get; set; }
        public string MEMO { get; set; }
        public string FLAG_GUID { get; set; }
        public string LANGUAGEID { get; set; }
    }
}
