//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_temp_area_paet_warehouse
    {
        public string id { get; set; }
        public string 区域名称 { get; set; }
        public string 物料编码 { get; set; }
        public string 储位编码 { get; set; }
        public string 仓库编码 { get; set; }
    }
}
