//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_temp_base_area
    {
        public string ID { get; set; }
        public string 区域名称 { get; set; }
        public string 备料储位编号 { get; set; }
        public string 备料储位名称 { get; set; }
        public string 是否超发 { get; set; }
    }
}
