//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TemporaryAreaCinv_Report
    {
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cspecifications { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string LKDate { get; set; }
        public string WarningDate { get; set; }
        public Nullable<int> Ageing { get; set; }
        public string Cycle { get; set; }
    }
}
