//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TEMP_IN_MO_INFO
    {
        public string 机种 { get; set; }
        public string 工单号 { get; set; }
        public string 工单量 { get; set; }
        public string 备料日期 { get; set; }
        public string 班别 { get; set; }
        public string 线体 { get; set; }
        public string 特殊 { get; set; }
        public string 二次用料 { get; set; }
        public string 部门编码 { get; set; }
        public string 计算工时 { get; set; }
        public string 上线日期 { get; set; }
    }
}
