//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_temp_base_client
    {
        public string id { get; set; }
        public string 客户编码 { get; set; }
        public string 客户名称 { get; set; }
        public string 状态 { get; set; }
        public string 联系人 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系地址 { get; set; }
        public string 客户类型 { get; set; }
        public string 助记码 { get; set; }
        public string 级别 { get; set; }
        public string 备注 { get; set; }
        public string ERP编码 { get; set; }
    }
}
