//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TRADETYPE
    {
        public string ID { get; set; }
        public string TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public string TRADETYPEID { get; set; }
        public string CERPCODE { get; set; }
        public string INOROUTNAME { get; set; }
        public string T { get; set; }
        public string ENABLE { get; set; }
        public string REMARK { get; set; }
    }
}
