//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WARNINGSTOCK_REPORT
    {
        public string cpartnumber { get; set; }
        public string cpartname { get; set; }
        public Nullable<decimal> iqty { get; set; }
        public string csafeqty { get; set; }
        public string csafeqtyceiling { get; set; }
        public int isalarm { get; set; }
    }
}
