//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WCS_TaskProcess
    {
        public string ID { get; set; }
        public string CTICKETCODE { get; set; }
        public string PACKAGENO { get; set; }
        public string TASKTYPE { get; set; }
        public string CSTATUS { get; set; }
        public string SOURCECODE { get; set; }
        public string CDEFIEND1 { get; set; }
        public string CDEFIEND2 { get; set; }
        public string CDEFIEND3 { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
        public Nullable<int> STEPS { get; set; }
        public string BeginSiteId { get; set; }
        public string EndSiteId { get; set; }
        public string StatusName { get; set; }
    }
}
