//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_get_stock_datecodenum
    {
        public string cinvcode { get; set; }
        public string cpositioncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public Nullable<decimal> OutNum { get; set; }
    }
}
