//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_get_handover_check
    {
        public string id { get; set; }
        public string cerpcode { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public Nullable<decimal> iqty { get; set; }
        public Nullable<decimal> qty_demand { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createowner { get; set; }
        public Nullable<decimal> out_qty { get; set; }
        public Nullable<decimal> hand_qty { get; set; }
        public Nullable<decimal> nohand_qty { get; set; }
        public Nullable<decimal> check_qty { get; set; }
        public Nullable<decimal> nocheck_qty { get; set; }
        public string sncode { get; set; }
    }
}
