//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_outbill_snreport
    {
        public Nullable<long> id { get; set; }
        public string CERPCODE { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CPOSITION { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public string SNCODE { get; set; }
        public string DATECODE { get; set; }
        public string weeks { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public System.DateTime DINDATE { get; set; }
        public string CWAREID { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
    }
}
