//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_transaction_sn
    {
        public Nullable<long> ID { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public string CPOSITIONCODE { get; set; }
        public string CPOSITION { get; set; }
        public string CTOPOSITIONCODE { get; set; }
        public string CTOPOSITION { get; set; }
        public string SN_CODE { get; set; }
        public Nullable<decimal> DATECODE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEOWNER { get; set; }
        public string STYPE { get; set; }
        public string weeks { get; set; }
        public string cerpcode { get; set; }
        public string typecode { get; set; }
        public string typename { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
        public string stypename { get; set; }
    }
}
