//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_position_stock_line
    {
        public Nullable<System.Guid> id { get; set; }
        public string line { get; set; }
        public Nullable<int> PosCount { get; set; }
        public Nullable<int> StockCount { get; set; }
        public Nullable<int> NoStockCount { get; set; }
        public string StockRatio { get; set; }
    }
}
