//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_inventory_turnin
    {
        public string ids { get; set; }
        public string stype { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string sncode { get; set; }
        public Nullable<decimal> datecode { get; set; }
        public string weeks { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public System.DateTime dindate { get; set; }
        public string cinpersoncode { get; set; }
        public string username { get; set; }
        public string worktype { get; set; }
        public string workTypeName { get; set; }
        public string stypename { get; set; }
    }
}
