//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARN_TEMP_STOCK_INFO
    {
        public string id { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string datecode { get; set; }
        public string cpositioncode { get; set; }
        public string cposition { get; set; }
        public string cwarecode { get; set; }
        public string cwarename { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> cshelflife { get; set; }
        public Nullable<decimal> dayspast { get; set; }
        public Nullable<System.DateTime> senddate { get; set; }
        public string cargocode { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string cdefine3 { get; set; }
        public string createuser { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
