//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCS_TaskProcess_D
    {
        public string IDS { get; set; }
        public string ID { get; set; }
        public string LOC { get; set; }
        public string NEWLOC { get; set; }
        public string MACHINE { get; set; }
        public string ASRSID { get; set; }
        public string CSTATUS { get; set; }
        public string CDEFIEND1 { get; set; }
        public string CDEFIEND2 { get; set; }
        public string CDEFIEND3 { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public string steps { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
    }
}
