//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCSAGVCallBackNotice
    {
        public string id { get; set; }
        public string reqcode { get; set; }
        public System.DateTime reqtime { get; set; }
        public string clientcode { get; set; }
        public string tokencode { get; set; }
        public string interfacename { get; set; }
        public string method { get; set; }
        public string taskcode { get; set; }
        public string wbcode { get; set; }
        public string podcode { get; set; }
        public string areacode { get; set; }
        public string materiallot { get; set; }
        public string currentpositioncode { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
