//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIPNEGATIVEISSUE_TEMP
    {
        public string id { get; set; }
        public string wip_entity_name { get; set; }
        public string wip_entity_id { get; set; }
        public string quantity_issued { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string inventory_item_id { get; set; }
    }
}
