//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_TABLE_RELATION
    {
        public string table_id { get; set; }
        public string table_name { get; set; }
        public string his_table { get; set; }
        public string child_table_id { get; set; }
        public Nullable<decimal> seq { get; set; }
        public string reservefield1 { get; set; }
        public string reservefield2 { get; set; }
        public string reservefield3 { get; set; }
    }
}
