//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRITE_BACK_TIME_SET
    {
        public string id { get; set; }
        public string type { get; set; }
        public string transaction_type { get; set; }
        public string cticketcode { get; set; }
        public Nullable<System.DateTime> exchange_time { get; set; }
        public Nullable<System.DateTime> expiration_time { get; set; }
        public string create_owner { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string last_upd_owner { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
    }
}
