//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZSICT1_USER
    {
        public string userno { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<decimal> sex { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<System.DateTime> lastmodifiedtime { get; set; }
        public string company { get; set; }
        public string rootdept { get; set; }
        public Nullable<decimal> comptype { get; set; }
        public Nullable<decimal> ddomain { get; set; }
        public string id { get; set; }
        public string emp_id { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
        public string extend4 { get; set; }
        public string extend5 { get; set; }
        public Nullable<decimal> extend6 { get; set; }
        public Nullable<decimal> extend7 { get; set; }
        public Nullable<decimal> extend8 { get; set; }
        public Nullable<decimal> extend9 { get; set; }
        public Nullable<decimal> extend10 { get; set; }
        public Nullable<System.DateTime> extend12 { get; set; }
        public Nullable<System.DateTime> extend13 { get; set; }
        public Nullable<System.DateTime> extend11 { get; set; }
        public string lastmodifieder { get; set; }
        public string login_guid { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string extend14 { get; set; }
        public string extend15 { get; set; }
        public string extend16 { get; set; }
        public string extend17 { get; set; }
        public string extend18 { get; set; }
        public byte[] blob1 { get; set; }
        public byte[] blob2 { get; set; }
        public byte[] blob3 { get; set; }
        public byte[] blob4 { get; set; }
        public byte[] blob5 { get; set; }
        public string filename_4_blob1 { get; set; }
        public string filename_4_blob2 { get; set; }
        public string filename_4_blob3 { get; set; }
        public string filename_4_blob4 { get; set; }
        public string filename_4_blob5 { get; set; }
        public string mime_type_4_blob1 { get; set; }
        public string mime_type_4_blob2 { get; set; }
        public string mime_type_4_blob3 { get; set; }
        public string mime_type_4_blob4 { get; set; }
        public string mime_type_4_blob5 { get; set; }
    }
}
